/* Sílabos investigados por Génesys para la consola de la Fase 3 (consola3.html · js/f3.js).
   Cuando la Escuela pulsa «Generar sílabo» en uno de estos cursos, el constructor recorre los momentos M1–M9
   con la traza de lo que Génesys revisó y entrega este sílabo en el formato del Generador de Sílabo BC v2.0.
   Cursos: SIS332 Big Data (ciclo 9 · 4 cr · 32 HT + 64 HP) y SIS333 Gobierno de Tecnologías de Información
   (ciclo 9 · 3 cr · 32 HT + 32 HP). Cada sesión es una semana de 16; las capacidades son las marcadas en la matriz. */
(function(){
const REC=i=>({C:true,M:true,GT:true,GP:true,GDAA:true,Q:i%2===1,R:true,V:i%3!==2});
function ses(u,i,a,ht,hp){
  const [tema,sub,prac,auto,ent,crit,fx,tarea]=a;
  return {n:i+1,tema,subtemas:sub.split('|'),ht,hp,prac,auto,ent,crit,hito:false,cierre:false,fx,tarea,micro:`TE-0${u}.${i+1}`,rec:REC(i)};
}
function unidad(n,U,ht,hp){
  const s=U.ses.map((a,i)=>ses(n,i,a,ht,hp));
  s[1].hito=true; s[s.length-1].hito=true; s[s.length-1].cierre=true;
  return {n,titulo:`Unidad ${n} · ${U.macro}`,macro:`TE-0${n} · ${U.macro}`,ra:U.ra,
    producto:{...U.prod,tipo:'Integrado',origen:'Parte del producto del curso: al integrarse con las otras unidades forma el producto funcional.'},
    criterios:U.crit,sesiones:s};
}
function temas(unidades,fuente){
  return unidades.map(u=>({id:`TE-0${u.n}`,nombre:u.macro.replace(/^TE-0\d · /,''),fx:u.sesiones[0].fx,
    micro:u.sesiones.filter(s=>!s.cierre).map((s,i)=>({id:s.micro,nombre:s.tema,sub:s.subtemas,origen:fuente,
      nivel:['Comprende','Aplica','Aplica','Domina','Domina'][i%5],fx:s.fx,tarea:s.tarea}))}));
}

/* ═════════════════════════ SIS332 · BIG DATA ═════════════════════════ */
const BD_U=[
 {macro:'Arquitectura y almacenamiento de datos masivos',
  ra:{titulo:'Diseño de la arquitectura de datos del caso',
    def:'Diseña la arquitectura lakehouse del caso asignado e implementa la ingesta distribuida de sus fuentes, justificando el almacenamiento, el formato y el particionamiento con criterios de volumen, velocidad y protección de datos personales.',
    origen:'F1 · T1.1 y T1.2 · capacidad E6 en nivel 3 · Bloom: Evaluar · Crear'},
  prod:{titulo:'Arquitectura de datos y capa bronce del caso',
    desc:'Documento de arquitectura (diagrama, decisiones y supuestos) y capa bronce del lakehouse con las fuentes del caso ingeridas en formato Parquet particionado, con su registro de ingesta.',
    entregables:['Ficha del caso: fuentes, volumen, velocidad, variedad y datos personales','Diagrama de arquitectura lakehouse con registro de decisiones (ADR)','Notebook de ingesta batch en PySpark y capa bronce en Parquet','Arquitectura y capa bronce sustentadas'],
    verificacion:['El diagrama distingue las capas bronce, plata y oro, y el flujo batch y en tiempo real.','Cada decisión de almacenamiento y formato está justificada con una medición o un criterio explícito.','La ingesta es reproducible: se ejecuta de principio a fin sin pasos manuales.','Los datos personales están identificados y tienen tratamiento declarado conforme a la Ley N.º 29733.'],
    formato:'Repositorio Git del equipo (notebooks, scripts y README) + documento de arquitectura en PDF · sustentación de 10 minutos'},
  crit:[{txt:'Diseña la arquitectura del caso justificando capas, formatos y particionamiento con criterios medibles de volumen y velocidad.',cap:'e6',fx:'F1',tarea:'T1.1'},
        {txt:'Construye la ingesta batch reproducible de todas las fuentes del caso hacia la capa bronce, con registro de ejecución.',cap:'e6',fx:'F1',tarea:'T1.2'}],
  ses:[
   ['Big Data y el ciclo de vida del dato','Las 5 V y el valor del dato en la organización|Arquitecturas lambda, kappa y lakehouse|Casos de Big Data en el Perú y datos abiertos del Estado|Ética y protección de datos personales (Ley N.º 29733)',
    'Analiza el caso asignado e identifica sus fuentes, el volumen, la velocidad y la variedad de sus datos, y los datos personales que contiene.',
    'Lee el capítulo 1 de Designing Data-Intensive Applications y completa la ficha del caso con la guía de aprendizaje autónomo.',
    'Ficha del caso','Caracteriza el caso con las 5 V y declara los datos personales y su base legal de tratamiento.','F1','T1.1'],
   ['Almacenamiento distribuido y formatos columnares','HDFS y almacenamiento de objetos|Formatos Parquet, ORC y Avro|Particionamiento y compresión|Del data lake al lakehouse con Delta Lake',
    'Compara en laboratorio el tamaño y el tiempo de lectura de una misma fuente en CSV, Parquet y Delta, y define la estrategia de particionamiento del caso.',
    'Redacta el registro de decisiones (ADR) del formato y el particionamiento con la evidencia medida en el laboratorio.',
    'Registro de decisiones de almacenamiento','Justifica el formato y el particionamiento con mediciones de tamaño y tiempo de lectura.','F1','T1.1'],
   ['Procesamiento distribuido con Apache Spark','De MapReduce a Spark|RDD, DataFrames y evaluación perezosa|Plan de ejecución, DAG, etapas y tareas|Entorno de trabajo: PySpark en Databricks o Docker',
    'Implementa en PySpark un conteo agregado sobre la fuente principal del caso y lee su plan de ejecución en la interfaz de Spark.',
    'Resuelve la guía práctica de transformaciones y acciones, y explica con sus palabras qué provoca cada etapa del DAG.',
    'Notebook de procesamiento distribuido','Ejecuta el procesamiento distribuido y explica el plan de ejecución con la interfaz de Spark.','F1','T1.2'],
   ['Ingesta batch y capa bronce','Fuentes: API REST, archivos de datos abiertos y bases relacionales|Esquemas explícitos y evolución del esquema|Ingesta incremental e idempotencia|Registro y control de la ingesta',
    'Construye la ingesta batch de las fuentes del caso hacia la capa bronce en Parquet particionado, con esquema explícito y registro de cada ejecución.',
    'Documenta el procedimiento de ingesta en el README del repositorio y verifica que se ejecute de principio a fin sin pasos manuales.',
    'Capa bronce del caso','Ingiere todas las fuentes del caso de forma reproducible, con esquema explícito y registro de ejecución.','F1','T1.2'],
   ['Cierre de la unidad: sustentación de la arquitectura y la capa bronce','Integración de la ficha, el ADR y la ingesta|Sustentación técnica ante el aula|Retroalimentación entre equipos y plan de mejora',
    'Sustenta la arquitectura lakehouse del caso y demuestra en vivo la ingesta hacia la capa bronce.',
    'Incorpora la retroalimentación recibida y publica la versión 1.0 de la arquitectura en el repositorio.',
    'Arquitectura y capa bronce sustentadas','Sustenta las decisiones de arquitectura con evidencia y responde las preguntas con precisión técnica.','F1','T1.1']]},
 {macro:'Ingeniería de datos a escala',
  ra:{titulo:'Construcción del dataset curado del caso',
    def:'Construye el dataset curado del caso transformando, validando y orquestando datos batch y en flujo con Spark, hasta obtener las capas plata y oro con calidad medida, linaje documentado y datos personales protegidos.',
    origen:'F1 · T1.2 y T1.3 · capacidad E6 en nivel 3 · Bloom: Evaluar · Crear'},
  prod:{titulo:'Dataset curado (capas plata y oro) con pipeline orquestado',
    desc:'Pipeline de datos orquestado que transforma la capa bronce en las capas plata y oro, con reglas de calidad automatizadas, un flujo en tiempo real y su diccionario de datos, listo para la analítica de la unidad 3.',
    entregables:['Transformaciones en Spark SQL y DataFrames hacia la capa plata','Informe de calidad del dato con reglas, métricas y linaje','Flujo en tiempo real con Kafka y Spark Structured Streaming','DAG de orquestación optimizado en Apache Airflow','Dataset curado sustentado'],
    verificacion:['La capa oro responde las preguntas del caso sin transformaciones adicionales.','Las reglas de calidad se ejecutan automáticamente y su resultado queda registrado.','El flujo en tiempo real procesa eventos con ventanas y marca de agua.','Los datos personales llegan seudonimizados o anonimizados a la capa oro.'],
    formato:'Repositorio Git con el DAG, los notebooks y el diccionario de datos + informe de calidad en PDF · demostración en vivo de 10 minutos'},
  crit:[{txt:'Construye las transformaciones y el flujo en tiempo real que llevan los datos del caso a las capas plata y oro, orquestados y reproducibles.',cap:'e6',fx:'F1',tarea:'T1.2'},
        {txt:'Evalúa la calidad del dataset con reglas automatizadas y métricas, y documenta el linaje y la protección de los datos personales.',cap:'e6',fx:'F1',tarea:'T1.3'},
        {txt:'Optimiza el pipeline con evidencia de la interfaz de Spark (particiones, caché y uniones) y reporta la mejora obtenida.',cap:'e7',fx:'F1',tarea:'T1.2'}],
  ses:[
   ['Transformación con Spark SQL y DataFrames','Uniones, agregaciones y funciones de ventana|Funciones definidas por el usuario y su costo|Modelado de la capa plata|Pruebas de las transformaciones',
    'Transforma la capa bronce del caso en la capa plata con Spark SQL y DataFrames, aplicando uniones y funciones de ventana.',
    'Escribe pruebas para dos transformaciones críticas y documenta en el diccionario las tablas de la capa plata.',
    'Capa plata del caso','Transforma los datos con uniones y ventanas correctas y verifica los resultados con pruebas.','F1','T1.2'],
   ['Calidad y gobierno del dato','Dimensiones de la calidad: completitud, exactitud, consistencia y oportunidad|Perfilado y reglas de calidad automatizadas|Linaje y catálogo de datos|Seudonimización y anonimización de datos personales',
    'Perfila el dataset del caso, automatiza las reglas de calidad y seudonimiza los datos personales antes de la capa oro.',
    'Elabora el informe de calidad con las métricas obtenidas, el linaje de las tablas y las acciones correctivas.',
    'Informe de calidad del dato','Mide la calidad con reglas automatizadas y protege los datos personales con la técnica justificada.','F1','T1.3'],
   ['Procesamiento en tiempo real','Apache Kafka: tópicos, particiones y consumidores|Spark Structured Streaming|Ventanas de tiempo y marca de agua (watermark)|Garantías de entrega y tolerancia a fallos',
    'Implementa un flujo en tiempo real que consume eventos del caso desde Kafka y calcula indicadores por ventana de tiempo.',
    'Explica en el informe cómo la marca de agua trata los eventos tardíos y qué garantía de entrega ofrece el flujo.',
    'Flujo en tiempo real del caso','Procesa eventos con ventanas y marca de agua, y explica la garantía de entrega del flujo.','F1','T1.2'],
   ['Orquestación y optimización del pipeline','Orquestación con Apache Airflow: DAG, tareas y dependencias|Particiones, caché y uniones por difusión (broadcast)|Lectura de la interfaz de Spark y cuellos de botella|Costos de cómputo y almacenamiento',
    'Orquesta el pipeline del caso en un DAG de Airflow y optimiza la transformación más costosa usando la evidencia de la interfaz de Spark.',
    'Reporta el tiempo de ejecución antes y después de la optimización y justifica cada ajuste aplicado.',
    'DAG orquestado y optimizado','Orquesta el pipeline completo y demuestra la mejora de desempeño con mediciones.','F1','T1.2'],
   ['Cierre de la unidad: sustentación del dataset curado','Integración de las capas plata y oro|Demostración en vivo del pipeline|Revisión cruzada de calidad entre equipos',
    'Demuestra en vivo el pipeline orquestado, desde la ingesta hasta la capa oro, y sustenta el informe de calidad.',
    'Corrige los hallazgos de la revisión cruzada y publica la versión 2.0 del dataset con su diccionario.',
    'Dataset curado sustentado','Demuestra el pipeline de extremo a extremo y sustenta la calidad del dataset con evidencia.','F1','T1.3']]},
 {macro:'Analítica y aprendizaje automático a escala',
  ra:{titulo:'Solución analítica a escala y propuesta de estrategia',
    def:'Evalúa modelos de aprendizaje automático entrenados de forma distribuida sobre el dataset curado del caso y sustenta ante la organización socia una estrategia basada en datos, con su impacto estimado y sus riesgos éticos.',
    origen:'F2 · T2.1–T2.2 y F3 · T3.1–T3.2 · capacidades E7 y E8 en nivel 3 · Bloom: Evaluar · Crear'},
  prod:{titulo:'Solución analítica de Big Data del caso',
    desc:'Producto integrador del curso: modelo de aprendizaje automático entrenado y evaluado con Spark MLlib, registrado en MLflow y desplegado en puntuación por lotes, con un tablero de decisión y un informe de recomendaciones estratégicas para la organización socia.',
    entregables:['Análisis exploratorio distribuido del dataset curado','Pipeline de aprendizaje automático en Spark MLlib','Informe de evaluación del modelo con métricas, sesgo y registro en MLflow','Puntuación desplegada y tablero de decisión','Informe de recomendaciones estratégicas','Solución analítica sustentada ante la organización socia'],
    verificacion:['El modelo supera la línea base declarada con la métrica acordada con la organización socia.','La evaluación incluye validación cruzada, análisis de sesgo y registro de experimentos.','El tablero responde las preguntas de negocio del caso.','Cada recomendación cita la evidencia que la sostiene y estima su impacto.'],
    formato:'Repositorio Git + tablero publicado + informe ejecutivo en PDF · sustentación de 15 minutos ante la organización socia'},
  crit:[{txt:'Genera modelos de aprendizaje automático distribuidos y los evalúa con validación cruzada, métricas y análisis de sesgo frente a una línea base.',cap:'e7',fx:'F2',tarea:'T2.2'},
        {txt:'Analiza patrones del dataset curado a escala y los interpreta en el contexto del caso.',cap:'e8',fx:'F3',tarea:'T3.1'},
        {txt:'Sustenta recomendaciones estratégicas basadas en la evidencia del modelo y del tablero, con su impacto estimado y sus riesgos éticos.',cap:'e8',fx:'F3',tarea:'T3.2'}],
  ses:[
   ['Análisis exploratorio distribuido','Estadística descriptiva a escala|Muestreo estratificado para la visualización|Correlaciones y detección de anomalías|Formulación de hipótesis de negocio',
    'Explora el dataset curado con agregaciones distribuidas y un muestreo estratificado, y formula tres hipótesis de negocio para el caso.',
    'Redacta el reporte exploratorio con las visualizaciones clave y las hipótesis priorizadas.',
    'Reporte exploratorio','Analiza el dataset con técnicas distribuidas y formula hipótesis de negocio sustentadas en los datos.','F3','T3.1'],
   ['Aprendizaje automático con Spark MLlib','Pipelines, transformadores y estimadores|Ingeniería de características a escala|Modelos de clasificación y regresión distribuidos|Línea base y métrica de éxito del negocio',
    'Construye el pipeline de MLlib del caso, desde las características hasta el modelo, y lo compara con la línea base declarada.',
    'Justifica la elección de la métrica de éxito con la pregunta de negocio del caso.',
    'Pipeline de aprendizaje automático','Entrena el modelo distribuido con un pipeline reproducible y lo compara con la línea base.','F2','T2.1'],
   ['Evaluación, ajuste y seguimiento de modelos','Validación cruzada y búsqueda de hiperparámetros|Métricas de desempeño e interpretación|Sesgo y equidad del modelo|Registro de experimentos con MLflow',
    'Ajusta el modelo con validación cruzada, analiza su sesgo por grupos y registra cada experimento en MLflow.',
    'Elabora el informe de evaluación con la comparación de experimentos y las limitaciones del modelo.',
    'Informe de evaluación del modelo','Evalúa y ajusta el modelo con métricas, sesgo y experimentos registrados.','F2','T2.2'],
   ['Despliegue y consumo de la analítica','Puntuación por lotes y en flujo|Publicación de resultados en la capa oro|Tablero de decisión para el usuario|Monitoreo de la deriva del modelo',
    'Despliega la puntuación del modelo sobre la capa oro y construye el tablero de decisión para la organización socia.',
    'Valida el tablero con un representante de la organización socia y registra sus observaciones.',
    'Tablero de decisión','Despliega la puntuación y construye un tablero que responde las preguntas de negocio del caso.','F3','T3.1'],
   ['De los datos a la decisión','Narrativa con datos|Estimación del impacto y del valor para la organización|Riesgos éticos, privacidad y uso responsable|Recomendaciones y hoja de ruta de adopción',
    'Formula las recomendaciones estratégicas del caso con la evidencia del modelo y del tablero, y estima su impacto.',
    'Redacta el informe ejecutivo de recomendaciones con su hoja de ruta de adopción.',
    'Informe de recomendaciones estratégicas','Propone estrategias sustentadas en evidencia, con impacto estimado y riesgos declarados.','F3','T3.2'],
   ['Cierre del curso: sustentación de la solución analítica','Integración de las tres unidades en el producto del curso|Sustentación ante la organización socia|Retroalimentación y lecciones aprendidas',
    'Sustenta ante la organización socia la solución analítica completa, desde la arquitectura hasta las recomendaciones.',
    'Entrega la versión final del producto integrador con la retroalimentación incorporada y sus lecciones aprendidas.',
    'Solución analítica sustentada','Sustenta la solución completa con dominio técnico y responde las preguntas de la organización socia.','F3','T3.2']]}
];
const BD_UNI=BD_U.map((U,i)=>unidad(i+1,U,2,4));
const SIS332={
  generado:true,clase:'Integrado',banco:'datos-bigdata',
  ref:'Investigación de Génesys: Big Data y Ciencia de Datos (UPM · UPC Barcelona · UTEC) · ACM/IEEE CS2023, áreas DM y PDC · EDISON Data Science Framework · CRISP-DM',
  sumilla:'Big Data es una asignatura de especialidad, de naturaleza teórico-práctica, del noveno ciclo de Ingeniería de Sistemas. Pertenece a la línea de Ciencia de datos e inteligencia artificial y tiene como prerrequisito Inteligencia Artificial (SIS329). Desarrolla las capacidades de construir datasets confiables a escala, generar modelos de inteligencia analítica distribuidos y convertir sus resultados en estrategias para la organización. Comprende tres unidades: arquitectura y almacenamiento de datos masivos; ingeniería de datos a escala, en lotes y en tiempo real; y analítica y aprendizaje automático distribuido. El estudiante trabaja con Apache Spark, Kafka, Airflow, Delta Lake y MLflow sobre un caso real de una organización socia con datos abiertos del Estado peruano, y construye por unidades una solución analítica de Big Data que sustenta al final del curso, con criterios de calidad, eficiencia, ética y protección de datos personales.',
  funciones:[
   {id:'F1',nombre:'Construcción de datasets confiables a escala',producto:'Dataset curado en arquitectura lakehouse, con pipeline orquestado',evidencia:'Pipeline reproducible con reglas de calidad ejecutadas, linaje documentado y datos personales protegidos',
    tareas:[{id:'T1.1',txt:'Diseña la arquitectura de datos del caso (capas, formatos y particionamiento) con criterios de volumen y velocidad.'},
            {id:'T1.2',txt:'Construye pipelines distribuidos de ingesta y transformación, en lotes y en tiempo real, orquestados y optimizados.'},
            {id:'T1.3',txt:'Asegura la calidad del dato y la protección de los datos personales con reglas automatizadas y linaje.'}]},
   {id:'F2',nombre:'Generación de modelos de inteligencia analítica a escala',producto:'Modelo de aprendizaje automático distribuido, evaluado y registrado',evidencia:'Experimentos registrados en MLflow con métricas, validación cruzada y análisis de sesgo frente a la línea base',
    tareas:[{id:'T2.1',txt:'Entrena modelos de aprendizaje automático distribuidos con pipelines de Spark MLlib.'},
            {id:'T2.2',txt:'Evalúa, ajusta y registra los modelos con validación cruzada, métricas de desempeño y análisis de sesgo.'}]},
   {id:'F3',nombre:'Analítica de datos masivos para la decisión',producto:'Tablero de decisión e informe de recomendaciones estratégicas',evidencia:'Recomendaciones validadas por la organización socia, con la evidencia que las sostiene y su impacto estimado',
    tareas:[{id:'T3.1',txt:'Analiza patrones en datos masivos y los publica en un tablero de decisión para el usuario.'},
            {id:'T3.2',txt:'Comunica hallazgos y propone estrategias basadas en datos, con impacto estimado y riesgos éticos declarados.'}]}],
  temas:null,
  productoCurso:{titulo:'Solución analítica de Big Data del caso',
    desc:'Solución de extremo a extremo para una organización socia: arquitectura lakehouse con ingesta en lotes y en tiempo real (unidad 1), dataset curado con calidad medida y pipeline orquestado (unidad 2) y modelo de aprendizaje automático distribuido con tablero de decisión y recomendaciones estratégicas (unidad 3).',
    entregables:['Arquitectura de datos y capa bronce del caso (unidad 1)','Dataset curado (capas plata y oro) con pipeline orquestado (unidad 2)','Solución analítica con modelo, tablero y recomendaciones (unidad 3)'],
    origen:'Génesys contrastó sílabos de Big Data de universidades de referencia y el perfil «Ingeniero de datos / Científico de datos» del EDISON Data Science Framework: el producto que el mercado reconoce es un pipeline de datos a escala que termina en una decisión. Capacidades marcadas en la matriz: E6, E7 y E8 en nivel 3.'},
  raCurso:{titulo:'Construcción y sustentación de una solución analítica de Big Data',
    def:'Diseña, construye y sustenta una solución analítica de Big Data para una organización socia, integrando datasets confiables a escala, modelos de aprendizaje automático distribuidos y recomendaciones estratégicas basadas en evidencia, con criterios de calidad, eficiencia, ética y protección de datos personales.',
    origen:'Capacidades E6, E7 y E8 en nivel 3 (Bloom: Evaluar · Crear) y producto del curso.'},
  criteriosCurso:[
   {cap:'e6',txt:'Construye datasets confiables a escala: pipeline reproducible, calidad medida con reglas automatizadas, linaje documentado y datos personales protegidos.',fx:'F1',tarea:'T1.2',nivel:3},
   {cap:'e7',txt:'Genera modelos de inteligencia analítica distribuidos, evaluados con validación cruzada, métricas y análisis de sesgo frente a una línea base.',fx:'F2',tarea:'T2.2',nivel:3},
   {cap:'e8',txt:'Analiza los datos y define estrategias: recomendaciones sustentadas en evidencia, con impacto estimado y riesgos éticos declarados.',fx:'F3',tarea:'T3.2',nivel:3}],
  unidades:BD_UNI,
  estrategias:{
   didacticas:['Aprendizaje basado en proyectos sobre un caso real de una organización socia, con datos abiertos del Estado peruano','Laboratorios guiados semanales en PySpark, 4 horas prácticas por sesión','Aula invertida: lectura o video previo y práctica en clase','Revisión cruzada de código y de calidad entre equipos (pull requests)','Demostraciones en vivo y sustentación ante la organización socia'],
   recursos:['Apache Spark (PySpark, Spark SQL, Structured Streaming y MLlib)','Apache Kafka y Apache Airflow en contenedores Docker','Delta Lake y formato Parquet','MLflow para el registro de experimentos','Databricks Community Edition o Google Colab como entorno alternativo','Git y GitHub para el trabajo en equipo','Plataforma Nacional de Datos Abiertos (datosabiertos.gob.pe)'],
   ia:['IA generativa permitida como asistente de programación, con declaración de uso en cada entregable','El equipo debe explicar y probar todo código generado; lo que no pueda explicar no se califica','Prohibido cargar datos personales del caso en herramientas de IA externas'],
   modalidad:['Laboratorio de cómputo con acceso al clúster o al entorno en la nube','Grabación de las sesiones teóricas por 72 horas','Guía de aprendizaje autónomo por sesión (GDAA)','Tutoría asíncrona con respuesta en 24 horas y asesoría de equipo quincenal']},
  evaluacion:[
   ['Unidad 1','Arquitectura de datos y capa bronce del caso','Rúbrica analítica','Semana 5','20 %'],
   ['Unidad 2','Dataset curado con pipeline orquestado','Rúbrica analítica','Semana 10','25 %'],
   ['Unidad 3','Solución analítica de Big Data sustentada (producto integrador)','Rúbrica analítica y ficha de la organización socia','Semana 16','30 %'],
   ['Transversal','Laboratorios semanales (notebooks) y cuestionarios de lectura','Lista de cotejo y cuestionario','Semanas 1–15','15 %'],
   ['Transversal','Evaluación de desempeño individual: prueba práctica en Spark','Examen de desempeño','Semana 12','10 %']],
  evalNota:'La nota del producto de equipo se individualiza con la coevaluación y con las preguntas de la sustentación. Nota mínima aprobatoria: 12 (escala vigesimal). Asistencia mínima: 70 %.',
  referencias:[
   'Kleppmann, M. (2017). Designing data-intensive applications. O’Reilly Media.',
   'Chambers, B., y Zaharia, M. (2018). Spark: The definitive guide. O’Reilly Media.',
   'Damji, J. S., Wenig, B., Das, T., y Lee, D. (2020). Learning Spark: Lightning-fast data analytics (2.ª ed.). O’Reilly Media.',
   'Reis, J., y Housley, M. (2022). Fundamentals of data engineering. O’Reilly Media.',
   'White, T. (2015). Hadoop: The definitive guide (4.ª ed.). O’Reilly Media.',
   'Marz, N., y Warren, J. (2015). Big data: Principles and best practices of scalable realtime data systems. Manning.',
   'Provost, F., y Fawcett, T. (2013). Data science for business. O’Reilly Media.',
   'Chapman, P., Clinton, J., Kerber, R., Khabaza, T., Reinartz, T., Shearer, C., y Wirth, R. (2000). CRISP-DM 1.0: Step-by-step data mining guide. SPSS.',
   'Congreso de la República del Perú. (2011). Ley N.º 29733, Ley de Protección de Datos Personales, y su reglamento.',
   'Documentación oficial de Apache Spark, Apache Kafka, Apache Airflow, Delta Lake y MLflow (versión vigente).']
};
SIS332.temas=temas(BD_UNI,'investigación de Génesys: sílabos de referencia y EDISON Data Science Framework');

/* ═════════════════ SIS333 · GOBIERNO DE TECNOLOGÍAS DE INFORMACIÓN ═════════════════ */
const GT_U=[
 {macro:'Fundamentos y diagnóstico del gobierno de TI',
  ra:{titulo:'Diagnóstico del gobierno de TI de la organización',
    def:'Evalúa el gobierno y la gestión de TI de la organización socia con ISO/IEC 38500 y COBIT 2019: prioriza sus objetivos con la cascada de metas y los factores de diseño, y mide la capacidad de sus procesos críticos con evidencia.',
    origen:'F1 · T1.1 · capacidad E1 en nivel 3 · Bloom: Evaluar · Crear'},
  prod:{titulo:'Informe de diagnóstico del gobierno de TI',
    desc:'Diagnóstico de la organización socia: contexto y metas empresariales, cascada de metas COBIT, perfil de factores de diseño, objetivos de gobierno priorizados y nivel de capacidad de sus procesos críticos, con las brechas priorizadas.',
    entregables:['Ficha de la organización: estrategia, estructura y rol de TI','Mapa de gobierno y gestión según el modelo EDM de ISO/IEC 38500','Cascada de metas y perfil de factores de diseño COBIT 2019','Evaluación de capacidad de procesos con evidencias y brechas','Informe de diagnóstico sustentado'],
    verificacion:['Distingue con precisión qué decisiones son de gobierno y cuáles de gestión.','La priorización de objetivos se deriva de la cascada de metas y de los factores de diseño, no de la opinión.','Cada nivel de capacidad está respaldado por evidencia documental o por entrevista registrada.','Las brechas se priorizan con criterios de impacto y urgencia explícitos.'],
    formato:'Informe en PDF según el formato institucional + hoja de cálculo de la herramienta de diseño COBIT · sustentación de 10 minutos'},
  crit:[{txt:'Evalúa el gobierno de TI de la organización socia con ISO/IEC 38500 y COBIT 2019, priorizando sus objetivos con la cascada de metas.',cap:'e1',fx:'F1',tarea:'T1.1'},
        {txt:'Mide la capacidad de los procesos críticos con evidencia y prioriza las brechas con criterios de impacto y urgencia.',cap:'e1',fx:'F1',tarea:'T1.1'}],
  ses:[
   ['Gobierno corporativo y gobierno de TI','Gobierno frente a gestión|ISO/IEC 38500: principios y modelo evaluar-dirigir-monitorear|Responsabilidad del directorio y del comité de TI|Valor, riesgo y recursos como fin del gobierno de TI',
    'Analiza el caso de la organización socia y clasifica sus decisiones de TI en decisiones de gobierno y de gestión según el modelo EDM.',
    'Lee el capítulo 1 de Enterprise Governance of Information Technology y elabora la ficha de la organización socia.',
    'Ficha de la organización y mapa EDM','Distingue gobierno y gestión en el caso y ubica cada decisión en el modelo EDM.','F1','T1.1'],
   ['El marco COBIT 2019','Principios del sistema de gobierno y del marco|Los 40 objetivos de gobierno y gestión en cinco dominios|Componentes del sistema de gobierno|Relación con ITIL, ISO/IEC 27001 y PMBOK',
    'Relaciona los problemas de TI de la organización socia con los objetivos de gobierno y gestión de COBIT 2019 que les corresponden.',
    'Resuelve la guía de estudio de los cinco dominios de COBIT y responde el cuestionario de lectura.',
    'Matriz de problemas y objetivos COBIT','Relaciona cada problema del caso con el objetivo COBIT pertinente y justifica la relación.','F1','T1.1'],
   ['Cascada de metas y factores de diseño','Metas empresariales y metas de alineamiento|Cascada de metas de COBIT 2019|Los once factores de diseño|Priorización de los objetivos con la herramienta de diseño',
    'Aplica la cascada de metas y los factores de diseño de COBIT 2019 al caso y obtiene los objetivos de gobierno priorizados.',
    'Contrasta el resultado de la herramienta de diseño con la percepción de la organización socia y explica las diferencias.',
    'Cascada de metas y objetivos priorizados','Deriva los objetivos priorizados de la cascada de metas y de los factores de diseño del caso.','F1','T1.1'],
   ['Evaluación de la capacidad de los procesos','Modelo de capacidad de COBIT 2019 (niveles 0 a 5)|Actividades y evidencias por nivel|Entrevistas y revisión documental|Identificación y priorización de brechas',
    'Evalúa la capacidad de dos procesos críticos de la organización socia con evidencias documentales y entrevistas registradas.',
    'Consolida las brechas encontradas y priorízalas con una matriz de impacto y urgencia.',
    'Evaluación de capacidad y brechas','Asigna niveles de capacidad sustentados en evidencia y prioriza las brechas con criterio explícito.','F1','T1.1'],
   ['Cierre de la unidad: sustentación del diagnóstico','Integración del informe de diagnóstico|Sustentación ante el aula|Retroalimentación y plan de mejora',
    'Sustenta el diagnóstico del gobierno de TI de la organización socia y defiende la priorización de sus brechas.',
    'Incorpora la retroalimentación y entrega la versión final del informe de diagnóstico.',
    'Informe de diagnóstico sustentado','Sustenta el diagnóstico con evidencia y responde las preguntas con dominio de COBIT e ISO/IEC 38500.','F1','T1.1']]},
 {macro:'Diseño del sistema de gobierno de TI',
  ra:{titulo:'Diseño del modelo de gobierno de TI',
    def:'Diseña el sistema de gobierno de TI de la organización socia (estructuras, derechos de decisión, políticas, gestión de riesgos y del valor, y relación con la gestión de servicios), alineado con su estrategia y con la normativa peruana aplicable.',
    origen:'F1 · T1.2 · capacidad E1 en nivel 3 · Bloom: Evaluar · Crear'},
  prod:{titulo:'Modelo de gobierno de TI propuesto',
    desc:'Propuesta de sistema de gobierno para la organización socia: comité y estructuras de decisión con su matriz RACI, portafolio priorizado de TI con caso de negocio, políticas de riesgo y cumplimiento, y modelo de valor de los servicios de TI.',
    entregables:['Estructura de gobierno, arquetipos de decisión y matriz RACI','Portafolio de TI priorizado con un caso de negocio','Política de riesgos y matriz de cumplimiento normativo','Modelo de valor de los servicios de TI con acuerdos de nivel de servicio','Modelo de gobierno sustentado'],
    verificacion:['Cada decisión clave de TI tiene un responsable y un arquetipo de decisión definido.','La priorización del portafolio se sustenta en valor, riesgo y alineamiento con la estrategia.','La matriz de cumplimiento cita la norma, el requisito y el control que lo atiende.','El modelo es coherente con las brechas del diagnóstico de la unidad 1.'],
    formato:'Documento de diseño en PDF + matriz RACI y portafolio en hoja de cálculo · sustentación de 10 minutos'},
  crit:[{txt:'Diseña las estructuras, los derechos de decisión y las políticas de gobierno de TI coherentes con las brechas del diagnóstico.',cap:'e1',fx:'F1',tarea:'T1.2'},
        {txt:'Formula políticas de riesgo y cumplimiento de TI alineadas con COBIT, ISO/IEC 27001 y la normativa peruana aplicable.',cap:'e1',fx:'F1',tarea:'T1.3'},
        {txt:'Prioriza el portafolio de TI con un caso de negocio que estima costos, beneficios y riesgos.',cap:'e2',fx:'F2',tarea:'T2.1'}],
  ses:[
   ['Estructuras y derechos de decisión','Los arquetipos de decisión de Weill y Ross|Comité de TI y comités de dirección|Matriz RACI de las decisiones de TI|Rol del director de TI (CIO)',
    'Diseña la estructura de gobierno de TI de la organización socia y la matriz RACI de sus decisiones clave.',
    'Contrasta la estructura propuesta con los arquetipos de decisión de Weill y Ross y justifica la elección.',
    'Estructura de gobierno y matriz RACI','Asigna cada decisión clave de TI a un responsable y a un arquetipo de decisión sustentado.','F1','T1.2'],
   ['Estrategia y portafolio de TI','Alineamiento estratégico de TI|Gestión del portafolio y de los programas (COBIT APO05)|Caso de negocio y gestión de beneficios|Criterios de priorización: valor, riesgo y capacidad',
    'Prioriza el portafolio de iniciativas de TI de la organización socia y elabora el caso de negocio de la iniciativa principal.',
    'Estima los costos, los beneficios y los riesgos del caso de negocio y los presenta en el formato del curso.',
    'Portafolio priorizado y caso de negocio','Prioriza el portafolio con criterios explícitos y sustenta el caso de negocio con cifras.','F2','T2.1'],
   ['Riesgo y cumplimiento de TI','Gestión del riesgo de TI (COBIT APO12 e ISO 31000)|Controles de ISO/IEC 27001:2022|Normativa peruana: Ley de Protección de Datos Personales y Ley de Gobierno Digital|Matriz de cumplimiento',
    'Identifica y evalúa los riesgos de TI del caso y construye la matriz de cumplimiento normativo con sus controles.',
    'Redacta la política de gestión de riesgos de TI de la organización socia.',
    'Política de riesgos y matriz de cumplimiento','Evalúa los riesgos del caso y vincula cada requisito normativo con un control verificable.','F1','T1.3'],
   ['Gestión de servicios y creación de valor','Sistema de valor del servicio de ITIL 4|Cadena de valor del servicio|Acuerdos de nivel de servicio|Relación entre ITIL 4 y COBIT 2019',
    'Modela el sistema de valor de un servicio de TI crítico de la organización socia y define sus acuerdos de nivel de servicio.',
    'Explica cómo los objetivos COBIT priorizados se apoyan en las prácticas de ITIL 4 del servicio modelado.',
    'Modelo de valor del servicio y ANS','Modela la cadena de valor del servicio y define acuerdos de nivel de servicio medibles.','F1','T1.2'],
   ['Cierre de la unidad: sustentación del modelo de gobierno','Integración del modelo de gobierno|Sustentación ante un comité de TI simulado|Retroalimentación entre equipos',
    'Sustenta el modelo de gobierno de TI ante un comité simulado y defiende su coherencia con el diagnóstico.',
    'Ajusta el modelo según las observaciones del comité y entrega su versión final.',
    'Modelo de gobierno sustentado','Sustenta el modelo de gobierno y su coherencia con el diagnóstico ante el comité simulado.','F1','T1.2']]},
 {macro:'Implementación, medición y aseguramiento',
  ra:{titulo:'Plan de implementación y control del gobierno de TI',
    def:'Planifica la implementación del gobierno de TI de la organización socia como un proyecto con estándar reconocido, define su cuadro de mando y su esquema de aseguramiento, y lo sustenta ante la alta dirección como hoja de ruta ejecutable.',
    origen:'F1 · T1.3 y F2 · T2.1–T2.2 · capacidades E1 y E2 en nivel 3 · Bloom: Evaluar · Crear'},
  prod:{titulo:'Plan de gobierno de TI de la organización',
    desc:'Producto integrador del curso: hoja de ruta de implementación según el ciclo de COBIT, plan del proyecto con gestión de interesados y del cambio, cuadro de mando integral de TI y esquema de aseguramiento, integrados con el diagnóstico y el modelo de gobierno de las unidades anteriores.',
    entregables:['Hoja de ruta de implementación con iniciativas y logros tempranos','Plan del proyecto: alcance, cronograma, interesados y gestión del cambio','Cuadro de mando integral de TI con indicadores de desempeño y de riesgo','Esquema de aseguramiento y programa de auditoría','Lineamientos de gobierno de datos, IA y transformación digital','Plan de gobierno de TI sustentado ante la alta dirección'],
    verificacion:['La hoja de ruta atiende todas las brechas priorizadas en el diagnóstico.','El plan del proyecto tiene línea base de alcance, tiempo y costo, y un registro de interesados.','Cada indicador del cuadro de mando tiene fórmula, meta, fuente y responsable.','El esquema de aseguramiento distingue las tres líneas y define la evidencia a auditar.'],
    formato:'Plan ejecutivo en PDF + cronograma del proyecto + cuadro de mando en hoja de cálculo · sustentación de 15 minutos ante la alta dirección'},
  crit:[{txt:'Planifica el proyecto de implementación con línea base de alcance, tiempo y costo, gestión de interesados y del cambio organizacional.',cap:'e2',fx:'F2',tarea:'T2.1'},
        {txt:'Controla el avance del proyecto con indicadores y gestiona los cambios y los interesados con evidencia.',cap:'e2',fx:'F2',tarea:'T2.2'},
        {txt:'Define el cuadro de mando y el esquema de aseguramiento que permiten evaluar, dirigir y monitorear el desempeño y el riesgo de TI.',cap:'e1',fx:'F1',tarea:'T1.3'}],
  ses:[
   ['Hoja de ruta de implementación','Ciclo de implementación de COBIT en siete fases|Iniciativas, dependencias y secuencia|Logros tempranos (quick wins)|Factores críticos de éxito',
    'Elabora la hoja de ruta de implementación del gobierno de TI de la organización socia a partir de sus brechas priorizadas.',
    'Verifica que cada brecha del diagnóstico tenga al menos una iniciativa en la hoja de ruta.',
    'Hoja de ruta de implementación','Construye la hoja de ruta con iniciativas secuenciadas que cubren todas las brechas priorizadas.','F1','T1.3'],
   ['Gestión del proyecto de implementación','Principios y dominios de desempeño del PMBOK 7|Alcance, EDT, cronograma y presupuesto|Registro y compromiso de los interesados|Gestión del cambio organizacional',
    'Planifica el proyecto de implementación con su EDT, cronograma, presupuesto y registro de interesados.',
    'Diseña la estrategia de gestión del cambio organizacional para los interesados de mayor influencia.',
    'Plan del proyecto de implementación','Establece la línea base del proyecto y una estrategia de interesados y de cambio coherente.','F2','T2.1'],
   ['Medición del desempeño de TI','Cuadro de mando integral de TI|Indicadores de desempeño (KPI) y de riesgo (KRI)|Metas, fórmulas, fuentes y responsables|Seguimiento del avance del proyecto con valor ganado',
    'Diseña el cuadro de mando integral de TI de la organización socia y calcula el avance del proyecto con valor ganado.',
    'Documenta la ficha técnica de cada indicador del cuadro de mando.',
    'Cuadro de mando integral de TI','Define indicadores con fórmula, meta, fuente y responsable, y controla el avance con valor ganado.','F2','T2.2'],
   ['Aseguramiento y auditoría del gobierno de TI','Objetivos MEA01, MEA02 y MEA03 de COBIT|Modelo de las tres líneas del IIA|Programa de auditoría del gobierno de TI|Comunicación de hallazgos al directorio',
    'Diseña el esquema de aseguramiento del gobierno de TI y el programa de auditoría de un objetivo priorizado.',
    'Simula la comunicación de dos hallazgos al comité de auditoría con su recomendación.',
    'Esquema de aseguramiento y programa de auditoría','Distingue las tres líneas y define la evidencia y la prueba de cada control a auditar.','F1','T1.3'],
   ['Gobierno de datos, IA y transformación digital','Gobierno de datos y del ciclo de vida del dato|Gobierno y uso responsable de la inteligencia artificial|Marco de Gobierno Digital del Perú (Decreto Legislativo N.º 1412)|Innovación y adopción de tecnologías emergentes',
    'Formula los lineamientos de gobierno de datos y de uso responsable de la IA de la organización socia, alineados con el marco de gobierno digital.',
    'Integra los lineamientos al plan de gobierno de TI y prepara la sustentación final.',
    'Lineamientos de gobierno de datos e IA','Formula lineamientos aplicables y alineados con la normativa y con la estrategia de la organización.','F1','T1.2'],
   ['Cierre del curso: sustentación del plan de gobierno de TI','Integración de las tres unidades en el producto del curso|Sustentación ante la alta dirección de la organización socia|Retroalimentación y lecciones aprendidas',
    'Sustenta el plan de gobierno de TI ante la alta dirección de la organización socia y responde sus preguntas.',
    'Entrega la versión final del producto integrador con la retroalimentación incorporada y sus lecciones aprendidas.',
    'Plan de gobierno de TI sustentado','Sustenta el plan completo con dominio de los marcos y responde con precisión a la alta dirección.','F2','T2.2']]}
];
const GT_UNI=GT_U.map((U,i)=>unidad(i+1,U,2,2));
const SIS333={
  generado:true,clase:'Integrado',banco:'gobierno-ti',
  ref:'Investigación de Génesys: Gobierno de TI (sílabos UPC · UNI · PUCP · UTP) · COBIT 2019 · ISO/IEC 38500 · ITIL 4 · PMBOK 7 · Marco de Gobierno Digital del Perú',
  sumilla:'Gobierno de Tecnologías de Información es una asignatura de especialidad, de naturaleza teórico-práctica, del noveno ciclo de Ingeniería de Sistemas. Pertenece a la línea de Gestión e innovación de TI, tiene como prerrequisito Teoría de Sistemas (SIS328) y precede a Arquitectura Empresarial. Desarrolla las capacidades de alinear las TI con la estrategia y el valor de la organización y de dirigir proyectos de TI con estándares reconocidos. Comprende tres unidades: fundamentos y diagnóstico del gobierno de TI; diseño del sistema de gobierno; e implementación, medición y aseguramiento. El estudiante aplica COBIT 2019, ISO/IEC 38500, ITIL 4, ISO/IEC 27001 y el PMBOK en una organización socia real y construye por unidades un plan de gobierno de TI que sustenta ante su alta dirección, considerando la normativa peruana de protección de datos personales y de gobierno digital.',
  funciones:[
   {id:'F1',nombre:'Gobierno e innovación de TI',producto:'Sistema de gobierno de TI de la organización: diagnóstico, modelo y esquema de control',evidencia:'Plan de gobierno aprobado por la alta dirección, con objetivos priorizados, estructuras de decisión e indicadores',
    tareas:[{id:'T1.1',txt:'Diagnostica la capacidad de gobierno y gestión de TI de la organización con COBIT 2019 e ISO/IEC 38500.'},
            {id:'T1.2',txt:'Diseña el sistema de gobierno de TI: estructuras, derechos de decisión, políticas y modelo de valor.'},
            {id:'T1.3',txt:'Evalúa, dirige y monitorea el desempeño, el riesgo y el cumplimiento de TI con indicadores y aseguramiento.'}]},
   {id:'F2',nombre:'Gestión de proyectos de TI',producto:'Proyecto de implementación del gobierno de TI planificado y controlado',evidencia:'Plan del proyecto con línea base, registro de interesados y seguimiento con valor ganado',
    tareas:[{id:'T2.1',txt:'Planifica el portafolio y el proyecto de implementación con alcance, tiempo, costo e interesados.'},
            {id:'T2.2',txt:'Controla el avance, los cambios y los interesados del proyecto hasta su cierre.'}]}],
  temas:null,
  productoCurso:{titulo:'Plan de gobierno de TI de la organización socia',
    desc:'Plan integral para una organización socia: diagnóstico de su gobierno de TI con COBIT 2019 e ISO/IEC 38500 (unidad 1), modelo de gobierno con estructuras, portafolio, riesgos y valor de los servicios (unidad 2) y hoja de ruta de implementación gestionada como proyecto, con cuadro de mando y aseguramiento (unidad 3).',
    entregables:['Informe de diagnóstico del gobierno de TI (unidad 1)','Modelo de gobierno de TI propuesto (unidad 2)','Plan de implementación, medición y aseguramiento (unidad 3)'],
    origen:'Génesys contrastó sílabos de Gobierno de TI de universidades peruanas de referencia con el ciclo de implementación de COBIT 2019: el producto profesional reconocible es el plan de gobierno de TI que una organización puede aprobar y ejecutar. Capacidades marcadas en la matriz: E1 y E2 en nivel 3.'},
  raCurso:{titulo:'Formulación y sustentación del plan de gobierno de TI',
    def:'Formula y sustenta ante la alta dirección el plan de gobierno de TI de una organización real, integrando el diagnóstico con marcos reconocidos, el diseño de su sistema de gobierno y la gestión de su implementación como proyecto, con indicadores de valor, riesgo y cumplimiento.',
    origen:'Capacidades E1 y E2 en nivel 3 (Bloom: Evaluar · Crear) y producto del curso.'},
  criteriosCurso:[
   {cap:'e1',txt:'Alinea las TI con la estrategia y el valor de la organización: diagnóstico con evidencia, sistema de gobierno coherente y esquema de indicadores y aseguramiento.',fx:'F1',tarea:'T1.2',nivel:3},
   {cap:'e2',txt:'Planifica y controla el proyecto de implementación con línea base de alcance, tiempo y costo, gestión de interesados y seguimiento con valor ganado.',fx:'F2',tarea:'T2.1',nivel:3}],
  unidades:GT_UNI,
  estrategias:{
   didacticas:['Aprendizaje basado en un caso real: cada equipo trabaja con una organización socia (empresa, municipalidad o institución educativa)','Talleres prácticos con la herramienta de diseño de COBIT 2019','Estudio de casos de gobierno de TI y análisis de noticias de fallas de gobierno','Juego de roles: comité de TI y comité de auditoría simulados','Sustentación ejecutiva ante la alta dirección de la organización socia'],
   recursos:['COBIT 2019: Introduction and Methodology, Governance and Management Objectives y Design Guide, con su herramienta de diseño','ISO/IEC 38500 e ISO/IEC 27001:2022','ITIL 4 Foundation y PMBOK 7','Plantillas del curso: matriz RACI, caso de negocio, cuadro de mando y programa de auditoría','MS Project o ProjectLibre para el cronograma','Normativa peruana: Ley N.º 29733 y Decreto Legislativo N.º 1412'],
   ia:['IA generativa permitida para la búsqueda y la redacción preliminar, con declaración de uso en cada entregable','Toda cifra, cita de norma o dato de la organización debe verificarse en la fuente original','No se comparte información confidencial de la organización socia con herramientas de IA externas'],
   modalidad:['Convenio o carta de colaboración con la organización socia al inicio del curso','Grabación de las sesiones teóricas por 72 horas','Guía de aprendizaje autónomo por sesión (GDAA)','Tutoría asíncrona con respuesta en 24 horas y asesoría de equipo quincenal']},
  evaluacion:[
   ['Unidad 1','Informe de diagnóstico del gobierno de TI','Rúbrica analítica','Semana 5','20 %'],
   ['Unidad 2','Modelo de gobierno de TI propuesto','Rúbrica analítica','Semana 10','25 %'],
   ['Unidad 3','Plan de gobierno de TI sustentado ante la alta dirección (producto integrador)','Rúbrica analítica y ficha de la organización socia','Semana 16','30 %'],
   ['Transversal','Talleres semanales y cuestionarios de lectura de los marcos','Lista de cotejo y cuestionario','Semanas 1–15','15 %'],
   ['Transversal','Evaluación individual de un caso de gobierno de TI','Examen de desempeño','Semana 12','10 %']],
  evalNota:'La nota del producto de equipo se individualiza con la coevaluación y con las preguntas de la sustentación. Nota mínima aprobatoria: 12 (escala vigesimal). Asistencia mínima: 70 %.',
  referencias:[
   'ISACA. (2018). COBIT 2019 framework: Introduction and methodology. ISACA.',
   'ISACA. (2018). COBIT 2019 framework: Governance and management objectives. ISACA.',
   'ISACA. (2018). COBIT 2019 design guide: Designing an information and technology governance solution. ISACA.',
   'ISO/IEC. (2015). ISO/IEC 38500:2015 Information technology — Governance of IT for the organization. ISO.',
   'ISO/IEC. (2022). ISO/IEC 27001:2022 Information security, cybersecurity and privacy protection — Information security management systems — Requirements. ISO.',
   'Weill, P., y Ross, J. W. (2004). IT governance: How top performers manage IT decision rights for superior results. Harvard Business School Press.',
   'De Haes, S., y Van Grembergen, W. (2015). Enterprise governance of information technology: Achieving alignment and value (2.ª ed.). Springer.',
   'AXELOS. (2019). ITIL foundation: ITIL 4 edition. TSO.',
   'Project Management Institute. (2021). Guía de los fundamentos para la dirección de proyectos (Guía del PMBOK) (7.ª ed.). PMI.',
   'The Institute of Internal Auditors. (2020). El modelo de las tres líneas del IIA 2020. IIA.',
   'Presidencia del Consejo de Ministros. (2018). Decreto Legislativo N.º 1412, Ley de Gobierno Digital, y su reglamento (Decreto Supremo N.º 029-2021-PCM).',
   'Congreso de la República del Perú. (2011). Ley N.º 29733, Ley de Protección de Datos Personales, y su reglamento.']
};
SIS333.temas=temas(GT_UNI,'investigación de Génesys: sílabos de referencia y ciclo de implementación de COBIT 2019');

/* Lo que Génesys revisó en cada momento del constructor (se muestra mientras genera) */
const TRAZA={
 SIS332:[
  'Nombre «Big Data» · ciclo 9 · 4 créditos · 32 HT + 64 HP de laboratorio · prerrequisito SIS329 Inteligencia Artificial · capacidades E6, E7 y E8 en nivel 3.',
  'Campo reconocido: ingeniería de datos y analítica a escala. Contrasté sílabos de Big Data de la UPM, la UPC Barcelona y la UTEC, las áreas DM y PDC de ACM/IEEE CS2023 y el EDISON Data Science Framework.',
  'El mercado reconoce como producto un pipeline de datos a escala que termina en una decisión: producto integrado «Solución analítica de Big Data» sobre un caso real con datos abiertos del Estado peruano.',
  'Un criterio por capacidad: E6 construye datasets confiables, E7 genera modelos distribuidos, E8 convierte resultados en estrategia.',
  'Resultado de aprendizaje en nivel 3 (Evaluar · Crear) y sumilla con la línea formativa, el prerrequisito y las herramientas: Spark, Kafka, Airflow, Delta Lake y MLflow.',
  'Tres macro temas: arquitectura y almacenamiento; ingeniería de datos en lotes y en tiempo real; analítica y aprendizaje automático distribuido. Quince micro temas con sus subtemas.',
  'Producto partido en tres entregas: capa bronce (semana 5), dataset curado (semana 10) y solución analítica (semana 16).',
  'Resultados y criterios por unidad trazados a las tareas T1.1–T3.2; se incluye la protección de datos personales (Ley N.º 29733) como criterio verificable.',
  'Dieciséis sesiones de 2 HT + 4 HP (32 + 64 horas), cada una con su laboratorio, su actividad autónoma y su entregable; evaluación con pesos y referencias verificables.'],
 SIS333:[
  'Nombre «Gobierno de Tecnologías de Información» · ciclo 9 · 3 créditos · 32 HT + 32 HP de taller · prerrequisito SIS328 Teoría de Sistemas · capacidades E1 y E2 en nivel 3.',
  'Campo reconocido: gobierno y gestión de TI. Contrasté sílabos de Gobierno de TI de la UPC, la UNI, la PUCP y la UTP con COBIT 2019, ISO/IEC 38500, ITIL 4 y el PMBOK 7.',
  'El producto profesional reconocible es el plan de gobierno de TI que la organización puede aprobar y ejecutar: producto integrado sobre una organización socia real.',
  'Un criterio por capacidad: E1 alinea las TI con la estrategia y el valor, E2 planifica y controla el proyecto de implementación.',
  'Resultado de aprendizaje en nivel 3 (Evaluar · Crear) y sumilla con la línea formativa, el prerrequisito, los marcos y la normativa peruana de gobierno digital.',
  'Tres macro temas siguiendo el ciclo de COBIT: diagnóstico; diseño del sistema de gobierno; implementación, medición y aseguramiento. Quince micro temas con sus subtemas.',
  'Producto partido en tres entregas: diagnóstico (semana 5), modelo de gobierno (semana 10) y plan de gobierno sustentado ante la alta dirección (semana 16).',
  'Resultados y criterios por unidad trazados a las tareas T1.1–T2.2; el cumplimiento normativo (Ley N.º 29733 y Decreto Legislativo N.º 1412) entra como criterio verificable.',
  'Dieciséis sesiones de 2 HT + 2 HP (32 + 32 horas), con taller, actividad autónoma y entregable por sesión; evaluación con pesos y referencias verificables.']
};

window.SILABOS_GENESYS={SIS332,SIS333,TRAZA};
})();
