/* Paso 1.1 · M1 · Consolidación de la Cartera de Especialidades a partir del barrido web del 23-09-2026.
   Uso: node herramientas/cartera-m1.js  →  datos/cartera-SIS.csv y datos/cartera-NUT.csv
   Procedencia: los conteos y cifras citados en los sustentos son datos verificables (ver datos/evidencias/<COD>-*.md);
   las puntuaciones 1–4 son juicio del modelo bajo las reglas del método (escalas declaradas en el skill del paso 1.1).
   Referencias: E = evidencia de empleo · P = prospectiva · N = normativa · O = oferta académica; el número remite a la lectura [L n]. */
const path=require("path");
const {escribir}=require("./cartera-csv");
const R=p=>path.join(__dirname,"..","datos",p);
const juicio="Conteos y cifras: dato verificable (evidencias). Puntuaciones 1–4: juicio del modelo bajo reglas declaradas.";

/* ═══════════════════ INGENIERÍA DE SISTEMAS ═══════════════════ */
const SIS=[
 {cod:"SIS-01",especialidad:"Desarrollo de software e ingeniería de aplicaciones",descripcion:"Construye el software que una organización usa: levanta requisitos, diseña, programa, prueba y lo pone en producción.",origen:"establecida",naturaleza:"desarrollo",
  empleo:4,empleo_txt:"Estado: «Especialista en desarrollo de sistemas» S/ 10 000–11 000 y «Analista programador» recurrentes en 2 089 vacantes públicas [E-L2]; LinkedIn «Desarrollador» 311 avisos [E-B12].",negocio:4,negocio_txt:"Fábricas de software y outsourcing (BairesDev, Inetum, Encora) y consultoras propias; oferta remota en USD [E-L1][E-L8][E-B13].",
  funciones_n:12,funciones:"Requisitos · modelado · arquitectura · backend · frontend · integración de APIs · pruebas · revisión de código · CI/CD · despliegue · mantenimiento · documentación",proceso:"Analizar → diseñar → construir → verificar → desplegar",evidencia:"Software desplegado en producción con su repositorio, pruebas automatizadas y documentación",
  d_vol:4,d_amp:4,d_esc:3,d_rem:3,d_for:2,t_cre:3,t_nor:2,t_inv:4,t_dem:3,t_tec:4,i_cri:3,i_alc:4,sos:3,
  fd:"Ingeniería de Sistemas de Información lidera la EDO 2025 con 5 226 puestos proyectados; banca, outsourcing, telecom, seguros y Estado convocan [E-L10][E-L1][E-L2]. Buk 2026: líder de desarrollo mediana S/ 8 300, arquitecto S/ 10 850 frente a S/ 4 331 del promedio joven [E-L11][E-L6]. Colegiatura exigida en el Estado, no visible en el privado [E-L2].",
  ft:"Demanda de desarrolladores +15 % en 2024 (Michael Page) con desaceleración en 2026 (NEO TI 22 → 15 %) [E-L7][P-L9]; inversión en IA 3,9x y VC de US$ 45,5 M a 76,5 M 2022–2025 [P-L4][P-L6][P-L12]; sin norma con plazo propia [N].",
  fi:"Sostiene banca, retail, telecom, salud y Estado; OIT ubica al software entre los trabajos cognitivos con exposición creciente a la IA: se automatiza código rutinario, no la arquitectura ni los requisitos [P-L10].",refs:"E-L1, E-L2, E-L7, E-L10, E-L11; P-L4, P-L9, P-L10; N-1; O-tabla",procedencia:juicio},
 {cod:"SIS-02",especialidad:"Ciencia de datos e inteligencia artificial",descripcion:"Convierte datos en decisiones y en modelos que aprenden: gobierna el dato, modela, entrena, evalúa y pone el modelo a operar.",origen:"emergente",naturaleza:"datos",
  empleo:4,empleo_txt:"LinkedIn Perú «Data Scientist» 844 vacantes [E-B10]; aviso Get on Board «Data Engineer, Lima, híbrido, US$ 1 500–2 500» (18-09-2026) [E-L8].",negocio:3,negocio_txt:"Consultoras de datos (Bluetab, Artefact) y trabajo remoto en USD; freelance sin cifra [E-L8].",
  funciones_n:9,funciones:"Ingesta · gobierno del dato · modelado · entrenamiento · validación · MLOps · monitoreo · comunicación de resultados · ética algorítmica",proceso:"Gobernar el dato → modelar → entrenar → evaluar → implantar",evidencia:"Modelo en producción con su informe de evaluación y su tablero de decisión",
  d_vol:4,d_amp:4,d_esc:4,d_rem:4,d_for:2,t_cre:4,t_nor:3,t_inv:4,t_dem:3,t_tec:3,i_cri:3,i_alc:4,sos:3,
  fd:"Banca, telcos, retail y consultoras convocan; +20 % de demanda en IA y big data en 2025 «con falta de profesionales»; 76 % de empleadores no encuentra talento en IA; déficit >2 700 científicos de datos [E-L7][E-L9][P-S]. Remuneración divergente: Indeed S/ 3 755, levels.fyi PEN 83 040 anuales [E-B10].",
  ft:"Gasto en IA US$ 497 M en 2025, +20 % anual hasta 2027; CAGR 21,1 % 2025–2029; 6 de 10 empresas en piloto o implementación [P-L3][P-S]. Ley 31814 y reglamento DS 115-2025-PCM con plazos de adecuación 2026–2029, sin presupuesto [N-4].",
  fi:"Es la especialidad que construye la automatización; se automatiza la exploración y el modelado estándar, no la definición del problema ni la gobernanza [P-L4].",refs:"E-L7, E-L8, E-L9; P-L3, P-L4; N-4; O-tabla",procedencia:juicio},
 {cod:"SIS-03",especialidad:"Ciberseguridad y gestión de riesgos digitales",descripcion:"Protege la información y los sistemas: evalúa riesgos, detecta, responde a incidentes y sostiene el cumplimiento.",origen:"establecida",naturaleza:"seguridad",
  empleo:4,empleo_txt:"Jefaturas y especialistas en banca, fintech, telecom y Fortinet; Buk 2026 jefe de ciberseguridad mediana S/ 11 380 [E-L11][E-L1]; ~123 ofertas contadas en 2023 [E-B7].",negocio:4,negocio_txt:"Servicios gestionados de seguridad y consultoras; la SBS exige evaluación independiente con certificaciones internacionales [N-3].",
  funciones_n:10,funciones:"Análisis de riesgos · vulnerabilidades · pruebas de penetración · SOC · respuesta a incidentes · forense · cumplimiento · concientización · continuidad · identidades",proceso:"Evaluar el riesgo → proteger → detectar → responder → recuperar",evidencia:"Informe de riesgos y plan de respuesta a incidentes aprobado por la organización",
  d_vol:3,d_amp:4,d_esc:4,d_rem:4,d_for:3,t_cre:4,t_nor:4,t_inv:3,t_dem:3,t_tec:3,i_cri:4,i_alc:4,sos:4,
  fd:"PCM: «brecha crítica de profesionales capacitados en ciberseguridad»; necesidad proyectada de 7 000–13 500 profesionales; 76 % de empleadores sin talento en IA y ciberseguridad [E-B7][E-L9]. Remuneración muy sobre el promedio (S/ 9 410–19 440) [E-L11].",
  ft:"748 M de intentos de ataque en el primer semestre de 2025; sector público principal blanco 2025 [P-L2][P-L1]. Impulso normativo con plazo: DS 126-2025-PCM (vigente 03-02-2026, reporte en 48 h), Res. SBS 504-2021, Res. 003-2023-PCM/SGTD (Oficial de Seguridad obligatorio) [N-2][N-3][N-8]. +15 % 2024, +20 % 2025 [E-L7].",
  fi:"Criticidad grave (servicios públicos, banca, salud); alcance nacional. Se automatiza el SOC de nivel 1; no la respuesta ni el gobierno del riesgo [P-L1].",refs:"E-L7, E-L9, E-L11; P-L1, P-L2; N-2, N-3, N-8; O-tabla",procedencia:juicio},
 {cod:"SIS-04",especialidad:"Infraestructura en la nube y DevOps",descripcion:"Diseña y automatiza la plataforma donde corre el software: nube, contenedores, pipelines y observabilidad.",origen:"establecida",naturaleza:"infraestructura",
  empleo:4,empleo_txt:"Aviso Valtx «Especialista de Infraestructura Cloud – AWS»: DevOps, CI/CD, FinOps, «planilla completa desde el primer día» [E-B8]; Estado «Especialista en infraestructura tecnológica» S/ 11 000 [E-L2].",negocio:3,negocio_txt:"Consultoras cloud (Valtx, Bluetab) y servicios gestionados [E-B8].",
  funciones_n:8,funciones:"Arquitectura cloud · infraestructura como código · contenedores · CI/CD · observabilidad · costos · automatización · respaldo",proceso:"Diseñar la plataforma → automatizar → operar → observar → optimizar",evidencia:"Plataforma operando con infraestructura como código, pipelines y tablero de observabilidad",
  d_vol:4,d_amp:4,d_esc:3,d_rem:4,d_for:2,t_cre:4,t_nor:2,t_inv:4,t_dem:3,t_tec:4,i_cri:3,i_alc:3,sos:3,
  fd:"Jobsora 617 avisos «aws», Glassdoor 91 «aws engineer» [E-B8]; consultoras, fintech, multinacionales y Estado; Buk jefe de infraestructura mediana S/ 7 190 (hasta 12 610) [E-L11]. Arquitectos cloud +15 % en 2024 [E-L7].",
  ft:"Demanda de nube híbrida +600 % en cinco meses (Red Hat); banca, telcos y gobierno lideran; data centers de US$ 100 M (ON) y anuncios de AWS en 2026 [P-L5][P-L11][P-S]. Sin norma con plazo propia; la SBS exige certificaciones ISO 27017/27018 a proveedores cloud [N-3].",
  fi:"Soporte de cargas de IA y servicios del Estado; se automatizan IaC y pipelines de rutina, la operación híbrida y regulada exige criterio [P-L4].",refs:"E-L2, E-L7, E-L11; P-L5, P-L11; N-3; O-tabla",procedencia:juicio},
 {cod:"SIS-05",especialidad:"Gestión de proyectos y servicios de TI",descripcion:"Dirige el proyecto tecnológico de principio a fin y opera el servicio bajo acuerdos de nivel.",origen:"establecida",naturaleza:"gestión TI",
  empleo:4,empleo_txt:"Glassdoor 52 avisos «PMO» en Lima; BeBee 598+ «gestión de proyectos»; consultoras buscan jefes de PMO para banca [E-B14]; Estado «Analista Scrum Master» [E-L2].",negocio:3,negocio_txt:"Consultoría de proyectos por programa y freelance (Freelancermap) [E-B13][E-B14].",
  funciones_n:9,funciones:"Planificación · alcance y cambio · dirección de equipos · control · proveedores · ITIL · acuerdos de nivel · mejora continua · reporte",proceso:"Planificar → dirigir → controlar → entregar → operar el servicio",evidencia:"Proyecto entregado con acta de cierre y catálogo de servicios operando bajo acuerdos de nivel",
  d_vol:4,d_amp:4,d_esc:2,d_rem:3,d_for:3,t_cre:2,t_nor:2,t_inv:3,t_dem:2,t_tec:3,i_cri:3,i_alc:3,sos:4,
  fd:"Buk 2026: gestión ágil de proyectos mediana S/ 7 290; Scrum Master S/ 5 646 [E-L11][E-B14]. Sin señal específica de escasez.",
  ft:"Sin serie propia; drivers: portafolio de IA (6 de 10 empresas en piloto) y Plan de Gobierno y Transformación Digital 2024–2026 [P-S]. Reglamento DL 1412 sin presupuesto adicional [N-5].",
  fi:"La ejecución de la inversión en IA depende de gestión; negociación y priorización no se automatizan [P-L4].",refs:"E-L2, E-L11; P-L4; N-5; O-tabla",procedencia:juicio},
 {cod:"SIS-06",especialidad:"Arquitectura empresarial y transformación digital",descripcion:"Alinea la tecnología con la estrategia: diagnostica la madurez digital y traza la hoja de ruta con su arquitectura objetivo.",origen:"emergente",naturaleza:"gestión TI",
  empleo:3,empleo_txt:"Sin conteo propio; puestos senior en banca y servicios de transformación; Buk: arquitecto de software S/ 10 850, subgerente TI S/ 12 210, CTO S/ 15 210 [E-L11][E-B14].",negocio:4,negocio_txt:"Consultoras de transformación digital y arquitectura; ProInnóvate apoya 30 000 pymes/año [P-S].",
  funciones_n:6,funciones:"Diagnóstico de madurez · alineamiento estrategia–tecnología · arquitectura objetivo · portafolio · gestión del cambio · medición del valor",proceso:"Diagnosticar → alinear → diseñar la arquitectura → priorizar → medir el valor",evidencia:"Hoja de ruta de transformación digital aprobada por la alta dirección con su arquitectura objetivo",
  d_vol:2,d_amp:3,d_esc:4,d_rem:4,d_for:3,t_cre:3,t_nor:3,t_inv:3,t_dem:3,t_tec:3,i_cri:3,i_alc:4,sos:4,
  fd:"71 % de empresas incorporó perfiles digitales en 2024; el perfil que «diseña arquitecturas que integran IA, nube y datos» lidera la EDO [E-L10][P-L7]. Remuneración muy sobre el promedio.",
  ft:"Política Nacional de Transformación Digital al 2030 (DS 085-2023-PCM) y Plan 2024–2026, sin presupuesto explícito [N-9][P-S]; 60 % de empresas evaluando IA [P-L4]; 7 de 10 planean automatización en 2026 [E-L5].",
  fi:"Sin arquitectura la inversión en IA se fragmenta; la decisión y el gobierno son humanos [P-L4].",refs:"E-L5, E-L10, E-L11; P-L4, P-L7; N-5, N-9; O-tabla",procedencia:juicio},
 {cod:"SIS-07",especialidad:"Desarrollo móvil y experiencias digitales",descripcion:"Construye aplicaciones móviles y experiencias digitales: diseña la experiencia, programa, publica y mide el uso.",origen:"establecida",naturaleza:"desarrollo",
  empleo:3,empleo_txt:"Se convoca dentro de equipos de producto de banca, telecom y fintech (Guinea Mobile/Cuy Móvil en Get on Board) [E-L8]; sin conteo propio.",negocio:4,negocio_txt:"Estudios de desarrollo y freelance de apps; fintech captura 76,9 % del capital de riesgo 2025 [P-S].",
  funciones_n:6,funciones:"Experiencia de usuario · desarrollo nativo y multiplataforma · integración · publicación · analítica · mantenimiento",proceso:"Analizar → diseñar la experiencia → construir → verificar → publicar",evidencia:"Aplicación publicada con sus métricas de uso y su registro de versiones",
  d_vol:3,d_amp:4,d_esc:2,d_rem:3,d_for:2,t_cre:3,t_nor:2,t_inv:3,t_dem:3,t_tec:4,i_cri:2,i_alc:3,sos:2,
  fd:"Sin cifra separada: los portales lo integran en «desarrollo de software»; la EDO nombra «desarrollo y mantenimiento de aplicaciones» [E-B15]. Remuneración de referencia la de desarrollo [E-L11].",
  ft:"39,4 M de líneas móviles; internet principalmente por celular; 5G en 5 ciudades [P-S][P-L11]. Tiende a fusionarse con desarrollo de software [P-L9].",
  fi:"Canal principal de banca digital y servicios; el front-end estándar es altamente automatizable [P-L10].",refs:"E-L8, E-L11; P-L10, P-L11; O-tabla",procedencia:juicio},
 {cod:"SIS-08",especialidad:"Consultoría e implementación de ERP (SAP)",descripcion:"Configura, integra y pone en marcha sistemas de gestión empresarial y sus procesos financieros y logísticos.",origen:"establecida",naturaleza:"gestión TI",
  empleo:4,empleo_txt:"Computrabajo con secciones activas «consultor SAP», «analista SAP», «analista funcional SAP»; aviso San Isidro «100 % presencial, SAP Hybris/Commerce Cloud» [E-B9].",negocio:4,negocio_txt:"Consultoría por proyecto e integradores; Freelancermap lista «ingeniería SAP» [E-B13].",
  funciones_n:7,funciones:"Levantamiento de procesos · configuración de módulos · integración · migración · pruebas · capacitación · soporte posimplantación",proceso:"Relevar el proceso → configurar → integrar → probar → poner en marcha",evidencia:"Sistema de gestión implantado con sus procesos configurados y acta de puesta en marcha",
  d_vol:3,d_amp:3,d_esc:3,d_rem:3,d_for:2,t_cre:2,t_nor:1,t_inv:3,t_dem:2,t_tec:4,i_cri:3,i_alc:3,sos:3,
  fd:"Consultor SAP S/ 2 000–10 000; Buk consultor ERP mediana S/ 6 420 [E-B9][E-L11]; retail, consultoras e integradores.",
  ft:"Sin cifras públicas de Perú; manufactura y minería adoptan IA en inventarios y cadena de suministro; 10+ proyectos mineros en 2026; migración a ERP en nube [P-L3][P-L7]. Sin norma.",
  fi:"Procesos financieros y logísticos de grandes empresas; configuración y reportes automatizables, rediseño e integración no [P].",refs:"E-B9, E-L11; P-L3, P-L7; O-tabla",procedencia:juicio},
 {cod:"SIS-09",especialidad:"Análisis funcional y de sistemas de información",descripcion:"Traduce las necesidades del negocio en requerimientos y especificaciones para los equipos de desarrollo.",origen:"establecida",naturaleza:"desarrollo",
  empleo:4,empleo_txt:"Secciones «analista funcional» activas; banca (Scotiabank), industria y Estado convocan «Analista de Sistemas» [E-B9][E-L1][E-L2].",negocio:2,negocio_txt:"Complemento de ingresos por encargo; sin evidencia de negocio escalable.",
  funciones_n:6,funciones:"Levantamiento · modelado de procesos · especificación · casos de uso · pruebas de aceptación · gestión del cambio",proceso:"Relevar → especificar → validar → acompañar la construcción",evidencia:"Documento de especificación de requisitos aprobado y casos de aceptación",
  d_vol:4,d_amp:4,d_esc:2,d_rem:2,d_for:3,t_cre:2,t_nor:2,t_inv:2,t_dem:2,t_tec:3,i_cri:2,i_alc:3,sos:2,
  fd:"La EDO nombra «analistas de sistemas de información» entre los más requeridos [E-B15]; remuneración S/ 2 000–4 600, bajo el promedio senior [E-B9].",
  ft:"Sin serie; la IA generativa absorbe documentación y especificación rutinaria [P-L10].",
  fi:"Criticidad moderada; alta exposición a la IA en tareas de documentación [P-L10].",refs:"E-L1, E-L2, E-B9; P-L10; O-tabla",procedencia:juicio},
 {cod:"SIS-10",especialidad:"Aseguramiento de calidad y pruebas de software",descripcion:"Prueba el software antes de que llegue al usuario: diseña casos, automatiza y certifica la versión.",origen:"establecida",naturaleza:"desarrollo",
  empleo:3,empleo_txt:"Sección «qa funcional» activa; QA S/ 3 500 «remoto o presencial» [E-B9]; Buk jefe de QA mediana S/ 6 740 [E-L11].",negocio:2,negocio_txt:"Sin evidencia de negocio propio.",
  funciones_n:5,funciones:"Casos de prueba · automatización · rendimiento · defectos · aseguramiento del proceso",proceso:"Recibir la versión → probar → reportar → certificar",evidencia:"Informe de pruebas con cobertura y certificación de la versión",
  d_vol:3,d_amp:3,d_esc:2,d_rem:2,d_for:2,t_cre:2,t_nor:1,t_inv:2,t_dem:2,t_tec:4,i_cri:3,i_alc:3,sos:2,
  fd:"Consultoras y banca; volumen medio con remuneración de entrada baja [E-B9].",
  ft:"Sin serie; es la especialidad de software con más tareas automatizables (generación de casos y scripts); riesgo de extinción del tester manual [P].",
  fi:"Calidad de apps financieras y estatales; el rol se desplaza a ingeniería de calidad [P-L10].",refs:"E-B9, E-L11; P-L10; O-tabla",procedencia:juicio},
 {cod:"SIS-11",especialidad:"Redes y telecomunicaciones",descripcion:"Diseña y opera la red que conecta a la organización: equipos, seguridad perimetral y disponibilidad.",origen:"establecida",naturaleza:"infraestructura",
  empleo:3,empleo_txt:"Avisos de Fortinet («Systems Engineer»), Bitel e Inetum en LinkedIn [E-L1]; sin conteo propio.",negocio:3,negocio_txt:"Integradores y contratistas de redes; servicios a minería [P-L11].",
  funciones_n:6,funciones:"Diseño de redes · configuración · seguridad perimetral · comunicaciones unificadas · monitoreo · soporte físico",proceso:"Diseñar la red → implementar → operar → asegurar la disponibilidad",evidencia:"Red operando con su documentación y sus indicadores de disponibilidad",
  d_vol:2,d_amp:3,d_esc:2,d_rem:2,d_for:3,t_cre:3,t_nor:2,t_inv:4,t_dem:3,t_tec:3,i_cri:3,i_alc:4,sos:4,
  fd:"Operadores, integradores y Estado; remuneración al promedio; sin conteo en portales [E-L1].",
  ft:"Inversión sectorial S/ 5 800 M en 2026 (+20–25 %); 5G con US$ 506 M mínimos de cuatro operadores y 437 localidades rurales; Bitel US$ 600 M en 20 años [P-L11]. Sin norma que habilite ni reserve (TUO Ley de Telecomunicaciones) [N-B12].",
  fi:"Conectividad de minas y servicios públicos; infraestructura física poco automatizable [P-L11].",refs:"E-L1; P-L11; N-B12; O-tabla",procedencia:juicio},
 {cod:"SIS-12",especialidad:"Auditoría de sistemas y gobierno de TI",descripcion:"Evalúa controles y riesgos de TI ante el comité de auditoría y sostiene el gobierno de la tecnología.",origen:"establecida",naturaleza:"gestión TI",
  empleo:3,empleo_txt:"Riesgo y cumplimiento de ciberseguridad 70k–100k anuales (Michael Page) [E-B5]; sin conteo de «auditor de sistemas» [E-B14].",negocio:3,negocio_txt:"Firmas de auditoría y consultoras; la SBS exige evaluación independiente del SGSI con certificaciones internacionales [N-3].",
  funciones_n:5,funciones:"Auditoría de controles · riesgos de TI · cumplimiento · COBIT · reporte al comité",proceso:"Planificar la auditoría → evaluar controles → reportar → seguir hallazgos",evidencia:"Informe de auditoría de sistemas con hallazgos y plan de remediación",
  d_vol:2,d_amp:2,d_esc:3,d_rem:3,d_for:4,t_cre:2,t_nor:4,t_inv:3,t_dem:2,t_tec:2,i_cri:4,i_alc:3,sos:4,
  fd:"Banca, seguros, contraloría y firmas de auditoría; exige colegiatura y certificación [N-1][N-3].",
  ft:"Res. SBS 504-2021 incorporó la evaluación de seguridad y sistemas a los reglamentos de auditoría; NTP-ISO/IEC 27001 obligatoria en el Estado con SGSI 2024–2026 [N-3][N-8]; auditoría de algoritmos de IA emergente [P].",
  fi:"Continuidad de servicios críticos del Estado; rol de control poco automatizable [P-L1].",refs:"E-B5; P-L1; N-1, N-3, N-8; O-tabla",procedencia:juicio},
 {cod:"SIS-13",especialidad:"Protección de datos personales y privacidad",descripcion:"Diseña e implementa el cumplimiento de datos personales: políticas, controles, incidentes y relación con la autoridad.",origen:"emergente",naturaleza:"seguridad",
  empleo:3,empleo_txt:"Figura de Oficial de Datos Personales obligatoria para entidades públicas, tratamientos masivos y datos sensibles (DS 016-2024-JUS art. 37) [N-6]; sin conteo en portales.",negocio:3,negocio_txt:"Consultoría de cumplimiento compartida con abogados [N-6].",
  funciones_n:5,funciones:"Inventario de tratamientos · política de seguridad · gestión de incidentes · derechos ARCO · relación con la ANPDP",proceso:"Inventariar → diseñar controles → operar → notificar → auditar",evidencia:"Programa de cumplimiento de datos personales con registro de incidentes y reportes a la autoridad",
  d_vol:2,d_amp:3,d_esc:3,d_rem:3,d_for:3,t_cre:2,t_nor:4,t_inv:2,t_dem:2,t_tec:2,i_cri:4,i_alc:4,sos:4,
  fd:"Demanda derivada de la obligación legal en todos los sectores; sin conteo específico en el barrido de empleo.",
  ft:"Ley 29733 y DS 016-2024-JUS (vigente 29-03-2025): Oficial de Datos obligatorio con entrada escalonada 2025–2028, notificación de incidentes en 48 h, ANPDP fiscaliza y sanciona [N-6].",
  fi:"Criticidad grave (sanciones, derechos de las personas); alcance nacional; la decisión y la relación con la autoridad no se automatizan.",refs:"N-6; O-tabla",procedencia:juicio},
 {cod:"SIS-14",especialidad:"Inteligencia de negocios y analítica empresarial",descripcion:"Construye reportes, tableros y análisis que sostienen decisiones de gerencia.",origen:"establecida",naturaleza:"datos",
  empleo:4,empleo_txt:"LinkedIn «Business Intelligence Analyst» 64–148 empleos [E-B12]; Buk jefe de BI mediana S/ 8 000 [E-L11].",negocio:3,negocio_txt:"Consultoría de analítica y tableros [E-L8].",
  funciones_n:5,funciones:"Modelado de datos · ETL · tableros · indicadores · análisis descriptivo",proceso:"Integrar → modelar → visualizar → analizar",evidencia:"Tablero de indicadores en operación con su modelo de datos documentado",
  d_vol:3,d_amp:4,d_esc:3,d_rem:3,d_for:2,t_cre:3,t_nor:2,t_inv:3,t_dem:3,t_tec:4,i_cri:3,i_alc:3,sos:2,
  fd:"Banca, retail y telcos [E-B10]; TI y datos tradicionales demandados por 78 % de empleadores TI [P-L9].",
  ft:"Adopción de IA exige gobernanza y calidad de datos [P-L4]; los tableros estándar se automatizan; converge con ciencia de datos [P].",
  fi:"Misma naturaleza que ciencia de datos: candidata a integración [O-tabla].",refs:"E-B12, E-L11; P-L4, P-L9; O-tabla",procedencia:juicio},
 {cod:"SIS-15",especialidad:"Internet de las cosas y sistemas embebidos",descripcion:"Conecta dispositivos físicos a plataformas de datos: programa el dispositivo y analiza sus sensores.",origen:"emergente",naturaleza:"infraestructura",
  empleo:2,empleo_txt:"Sin dato en ninguna búsqueda de empleo [E]; proyectos piloto en minería y agroindustria [P-L3].",negocio:3,negocio_txt:"Integradores de soluciones industriales; UPN lo dicta como curso [O-14].",
  funciones_n:5,funciones:"Dispositivos · programación embebida · protocolos · plataforma IoT · analítica de sensores",proceso:"Diseñar el dispositivo → conectar → integrar → analizar",evidencia:"Solución IoT operando con su plataforma y sus datos",
  d_vol:1,d_amp:2,d_esc:2,d_rem:3,d_for:2,t_cre:3,t_nor:1,t_inv:3,t_dem:4,t_tec:2,i_cri:3,i_alc:3,sos:4,
  fd:"Sin avisos en el barrido; se contrata dentro de proyectos de minería 4.0 [E][P-L3].",
  ft:"88 % de empresas evalúa IA en el edge; fibra a 24 minas; 5G como habilitador; industria 4.0 como driver estructural [P-S][P-L11]. Experimentación ligada a 5G.",
  fi:"Seguridad operacional minera e industrial (17 % de incidentes graves) [P-L1].",refs:"P-L1, P-L3, P-L11; O-14",procedencia:juicio},
 {cod:"SIS-16",especialidad:"Blockchain y activos digitales",descripcion:"Desarrolla y audita contratos inteligentes sobre redes distribuidas.",origen:"emergente",naturaleza:"desarrollo",
  empleo:1,empleo_txt:"Sin dato en ninguna búsqueda de empleo ni de prospectiva para Perú [E][P].",negocio:3,negocio_txt:"Proyectos puntuales en fintech; sin cifra.",
  funciones_n:3,funciones:"Contratos inteligentes · billeteras · auditoría",proceso:"Diseñar el contrato → desplegar → auditar",evidencia:"Contrato inteligente desplegado y auditado",
  d_vol:1,d_amp:1,d_esc:2,d_rem:3,d_for:1,t_cre:2,t_nor:1,t_inv:2,t_dem:2,t_tec:2,i_cri:2,i_alc:2,sos:2,
  fd:"Sin puestos con ese nombre en el país [E].",ft:"La búsqueda de prospectiva no arrojó información sobre blockchain en Perú; fintech captura el capital de riesgo sin blockchain como especialidad [P-S].",
  fi:"Bajo alcance; en extinción como especialidad autónoma [P].",refs:"P-S; O-tabla",procedencia:juicio},
 {cod:"SIS-17",especialidad:"Administración de bases de datos",descripcion:"Instala, afina y respalda las bases de datos que usan los sistemas.",origen:"establecida",naturaleza:"datos",
  empleo:3,empleo_txt:"Estado: «Especialista en administración de base de datos» recurrente, S/ 6 500–10 000 [E-L2]; sin conteo privado.",negocio:1,negocio_txt:"No sostiene negocio propio; se contrata dentro del equipo de plataforma.",
  funciones_n:3,funciones:"Instalación y afinamiento · respaldo y recuperación · seguridad de acceso",proceso:"Recibir el requerimiento → administrar → respaldar",evidencia:"Base de datos operando con su plan de respaldo",
  d_vol:2,d_amp:3,d_esc:2,d_rem:3,d_for:3,t_cre:1,t_nor:2,t_inv:2,t_dem:2,t_tec:4,i_cri:3,i_alc:3,sos:2,
  fd:"Estado y banca; el privado lo absorbe en DevOps y datos [E-L2].",ft:"Los servicios gestionados en la nube absorben la administración; se reconvierte a ingeniería de datos [P].",
  fi:"Integridad de datos financieros y estatales; el DBA operativo es altamente automatizable [P-L4].",refs:"E-L2; P-L4; O-tabla",procedencia:juicio},
 {cod:"SIS-18",especialidad:"Diseño de experiencia de usuario (UX/UI)",descripcion:"Investiga, diseña y valida la experiencia e interfaz de productos digitales.",origen:"establecida",naturaleza:"desarrollo",
  empleo:3,empleo_txt:"LinkedIn Perú «UI UX» 39–56 vacantes [E-B12].",negocio:4,negocio_txt:"Estudios de diseño y freelance.",
  funciones_n:5,funciones:"Investigación de usuarios · arquitectura de información · prototipado · pruebas de usabilidad · sistema de diseño",proceso:"Investigar → diseñar → prototipar → validar",evidencia:"Prototipo validado y sistema de diseño documentado",
  d_vol:2,d_amp:3,d_esc:2,d_rem:3,d_for:1,t_cre:2,t_nor:1,t_inv:2,t_dem:3,t_tec:3,i_cri:2,i_alc:3,sos:2,
  fd:"Volumen bajo y compartido con diseño gráfico; colegiatura no exigida [E-B12].",ft:"Sin serie; UTEC lo declara como concentración [O-5].",
  fi:"Campo compartido con diseño; en el límite del alcance que habilita el título de ingeniero [O-tabla].",refs:"E-B12; O-5",procedencia:juicio},
 {cod:"SIS-19",especialidad:"Soporte técnico y mesa de ayuda",descripcion:"Atiende incidencias de primer nivel y gestiona tickets.",origen:"en extinción",naturaleza:"infraestructura",
  empleo:3,empleo_txt:"Gran parte de los 163 avisos «ingeniero de sistemas sin experiencia» con base S/ 1 200 [E-B1]; clínicas, universidades y UGEL [E-L1][E-L2].",negocio:1,negocio_txt:"No sostiene negocio propio.",
  funciones_n:3,funciones:"Incidencias de primer nivel · instalación · tickets",proceso:"Recibir el ticket → resolver → cerrar",evidencia:"Ticket cerrado",
  d_vol:4,d_amp:3,d_esc:1,d_rem:1,d_for:1,t_cre:1,t_nor:1,t_inv:1,t_dem:2,t_tec:3,i_cri:2,i_alc:2,sos:1,
  fd:"Puesto técnico, no de ingeniero; remuneración muy bajo el promedio [E-B1][E-L11].",ft:"Los empleos de entrada son los primeros automatizados (OIT 2026); soporte nivel 1 en la franja de mayor exposición [P-S][P-L10].",
  fi:"Contracción como carrera universitaria; puerta de entrada técnica [P].",refs:"E-B1, E-L11; P-L10",procedencia:juicio},
 {cod:"SIS-20",especialidad:"IA generativa y automatización asistida",descripcion:"Atraviesa las funciones de todas las especialidades: generación de código, documentación, pruebas, análisis y soporte.",origen:"emergente",naturaleza:"transversal",
  empleo:1,empleo_txt:"No hay puestos con ese nombre: hay tareas asistidas dentro del trabajo del ingeniero; alfabetización en IA demandada por 82 % de empleadores TI [P-L9].",negocio:2,negocio_txt:"Complemento dentro de consultoría; no campo de ejercicio.",
  funciones_n:0,funciones:"Atraviesa varios procesos profesionales",proceso:"Atraviesa varios procesos profesionales",evidencia:"No entrega evidencia profesional propia",
  d_vol:2,d_amp:3,d_esc:3,d_rem:3,d_for:1,t_cre:4,t_nor:3,t_inv:4,t_dem:3,t_tec:3,i_cri:3,i_alc:4,sos:2,
  fd:"Competencia más demandada del sector TI (84 % desarrollo de IA, 82 % alfabetización) [P-L9].",ft:"CAGR de IA generativa 45,1 % 2025–2029; 50 % de grandes empresas la usa [P-S][P-L3]; Ley 31814 [N-4].",
  fi:"Tecnología habilitante: recurso de productividad del paso 2.2, no especialidad [método].",refs:"P-L3, P-L9; N-4",procedencia:juicio}
];

/* ═══════════════════ NUTRICIÓN HUMANA ═══════════════════ */
const NUT=[
 {cod:"NUT-01",especialidad:"Nutrición clínica hospitalaria",descripcion:"Atiende al paciente internado y ambulatorio: valora, diagnostica, prescribe el tratamiento nutricional y lo sigue hasta el alta.",origen:"establecida",naturaleza:"atención individual",
  empleo:4,empleo_txt:"Hospital Tarapoto, plaza 276 «Nutricionista» S/ 5 342: título, colegiatura y habilitación, 3 años de experiencia, especialización en nutrición hospitalaria, pediátrica, gestacional o soporte crítico (90 h) [E-9]; Auna, SANNA, Ricardo Palma convocan [E-13][E-7].",negocio:3,negocio_txt:"Consulta clínica privada presencial o virtual como sector de mayor demanda (La República 2026) [E-2].",
  funciones_n:12,funciones:"Tamizaje · valoración · diagnóstico · prescripción dietoterápica · soporte enteral · monitoreo · consejería al alta · interconsulta · registro en historia · auditoría · docencia · investigación",proceso:"Valorar → diagnosticar → tratar → seguir",evidencia:"Plan de atención nutricional individualizado y su registro en historia clínica",
  d_vol:4,d_amp:4,d_esc:3,d_rem:3,d_for:4,t_cre:3,t_nor:3,t_inv:3,t_dem:4,t_tec:2,i_cri:4,i_alc:4,sos:4,
  fd:"Jooble «nutricionista clínica» 9 103 avisos (cota superior de agregador); MINSA, EsSalud, DIRESA y clínicas privadas [E-13][E-1]. Remuneración pública S/ 5 342 (276) y CAS S/ 2 500–5 000 frente a S/ 3 738–4 913 del promedio [E-9][E-1][E-8]. Todos los avisos exigen colegiatura y habilitación [E-9].",
  ft:"Comorbilidad (obesidad, diabetes o HTA) en 15+ de 39,9 → 41,8 % (ENDES 2025); >80 000 cánceres nuevos/año; 3 M con ERC; 60+ = 14,3 % de la población [P-L1][P-L10][P-L9][P-S]. NTS 103 (RM 665-2013) vigente: UPSS de Nutrición obligatoria en 2.º y 3.er nivel, jefatura y consulta reservadas al nutricionista colegiado [N-3]. Contratos EsSalud por red [P-S]. IA hospitalaria en revisión sin validación local [P-L11].",
  fi:"Criticidad grave e irreversible; alcance nacional. Se automatiza tamizaje y cálculo, no el juicio clínico ni la responsabilidad de la prescripción [P-L11].",refs:"E-1, E-2, E-7, E-8, E-9, E-13; P-L1, P-L9, P-L10, P-L11; N-3; O-tabla",procedencia:juicio},
 {cod:"NUT-02",especialidad:"Gestión de servicios de alimentación e inocuidad",descripcion:"Dirige el servicio que alimenta a pacientes, trabajadores o escolares: planifica el menú, estandariza, asegura la inocuidad y audita.",origen:"establecida",naturaleza:"gestión de servicios",
  empleo:4,empleo_txt:"Newrest «Nutricionista colegiado campamento minero 14x7» (Pasco); Sodexo «Nutricionista Campamento Chincha 14x7»; NATCLAR «Licenciada en Nutrición habilitado indispensable» [E-7][E-12]; Sodexo exige colegiatura, habilidad, HACCP y carné de sanidad [E-B15].",negocio:4,negocio_txt:"Concesionarias y consultoría HACCP; negocio escalable (Sodexo 173 avisos, Newrest 13 años en Perú) [E-B15][E-B5].",
  funciones_n:10,funciones:"Planificación de menús · estandarización · costeo · compras · HACCP · puntos críticos · supervisión · auditoría sanitaria · no conformidades · indicadores",proceso:"Planificar → estandarizar → asegurar inocuidad → auditar",evidencia:"Plan HACCP y expediente de auditoría del servicio",
  d_vol:4,d_amp:4,d_esc:3,d_rem:2,d_for:3,t_cre:3,t_nor:3,t_inv:4,t_dem:3,t_tec:3,i_cri:4,i_alc:4,sos:4,
  fd:"Jooble «campamento minero» 4 102 (cota); 3 de 5 avisos destacados de LinkedIn son Newrest/Sodexo; regímenes 14x7 y 21x7 reiterados en Pasco, Pisco, Chincha, Apurímac [E-12][E-7]. Remuneración no publicada; auxiliares S/ 1 200 [E-7].",
  ft:"Programa de Alimentación Escolar 2026 con S/ 2 636,6 M, 4,2 M escolares y fichas técnicas obligatorias tras ~400 intoxicados en 2024 [P-L4]; licitaciones hospitalarias de EsSalud continuas [P-S]. Ley 30021 y DS 017-2017-SA vigentes; NTS 142 y HACCP obligatorio sin reserva profesional (nivel 2) [N-4]. Perú Compras y trazabilidad maduros [P].",
  fi:"4,2 M escolares y población hospitalizada; fallas = intoxicaciones masivas. Se automatiza planificación y costeo, no la auditoría in situ ni la responsabilidad sanitaria [P].",refs:"E-7, E-12, E-B5, E-B15; P-L4, P-S; N-4; O-tabla",procedencia:juicio},
 {cod:"NUT-03",especialidad:"Nutrición comunitaria y salud pública",descripcion:"Interviene sobre la nutrición de una población: diagnostica, planifica el programa, ejecuta y mide el impacto.",origen:"establecida",naturaleza:"salud poblacional",
  empleo:4,empleo_txt:"Convocatorias públicas: «Título Profesional en Nutrición… colegiado y habilitado», experiencia en programas alimentarios o salud pública; DIRESA, redes, municipalidades, Cuna Más (Lima 9+, Ica 3) [E-1]; RSVM Huancayo 5 nutricionistas [E-B2].",negocio:1,negocio_txt:"Dependiente del Estado; no sostiene negocio propio [E-1].",
  funciones_n:9,funciones:"Diagnóstico poblacional · vigilancia · diseño de intervención · consejería · capacitación de agentes · articulación · monitoreo · evaluación de impacto · programas presupuestales",proceso:"Diagnosticar población → planificar → intervenir → evaluar",evidencia:"Plan de intervención poblacional con línea de base e informe de impacto",
  d_vol:3,d_amp:3,d_esc:3,d_rem:2,d_for:4,t_cre:2,t_nor:3,t_inv:3,t_dem:4,t_tec:2,i_cri:4,i_alc:4,sos:4,
  fd:"74 vacantes públicas en el agregador; CAS S/ 2 500–5 000 [E-1]. Señal de escasez más fuerte del campo: el CNP alerta el recorte de plazas SERUMS 2026 en el primer nivel «donde la demanda es mayor»; 1 nutricionista por 6 000 hab. [E-3][E-5].",
  ft:"Desnutrición crónica estancada (11,7 → 12,1 %), anemia 6–35 m 43,4 %, rural 23 % vs urbana 8,2 %; suplementación y CRED al alza (I-2025) [P-L1][P-L15]. NTS 213 (RM 251-2024) y PPoR 1001; ejecución 2025–2026 no obtenida [N-3][N-12]. Plazas SERUMS a la baja [E-3].",
  fi:"~2 M de niños <5 y gestantes; 15 años de estancamiento en anemia con daño cognitivo irreversible. Visita domiciliaria y consejería intercultural no se automatizan [P].",refs:"E-1, E-3, E-5, E-B2; P-L1, P-L15; N-3, N-12; O-tabla",procedencia:juicio},
 {cod:"NUT-04",especialidad:"Nutrición pediátrica y materna",descripcion:"Atiende al niño y a la gestante en el primer nivel: crecimiento, anemia, lactancia y alimentación complementaria.",origen:"establecida",naturaleza:"atención individual",
  empleo:2,empleo_txt:"No aparece como puesto separado: Tarapoto admite «especialización pediátrica o gestacional» dentro de la plaza de nutricionista; Cuna Más convoca nutricionistas generales [E-9][E-1].",negocio:3,negocio_txt:"Consulta pediátrica privada; sin cifra [E].",
  funciones_n:8,funciones:"Antropometría infantil · lactancia y complementaria · anemia · desnutrición aguda · gestante · consejería familiar · seguimiento del crecimiento · CRED",proceso:"Valorar → diagnosticar → tratar → seguir (niño y gestante)",evidencia:"Plan de atención nutricional individualizado",
  d_vol:3,d_amp:3,d_esc:3,d_rem:2,d_for:4,t_cre:2,t_nor:4,t_inv:3,t_dem:4,t_tec:2,i_cri:4,i_alc:4,sos:4,
  fd:"Cuna Más 12+ vacantes; CAS S/ 2 500–5 000; 276 S/ 5 342 [E-1][E-9]. Anemia y desnutrición infantil citadas por el CNP como argumento de brecha [E-3].",
  ft:"Bajo peso al nacer 7,3 → 8,4 %, prematuridad 21,1 → 22,1 %, lactancia exclusiva 71,4 %; anemia 43,4 % [P-L15][P-L1]. NTS 213 anemia (RM 251-2024, mod. RM 429-2024) con tamizaje y suplementación nominal; PPoR 1001 [N-4][N-12].",
  fi:"~500 000 nacimientos/año y 2 M <5 años; error en los 1 000 días = daño permanente. Consejería de lactancia y manejo del prematuro no se automatizan [P].",refs:"E-1, E-3, E-9; P-L1, P-L15; N-4, N-12; O-tabla",procedencia:juicio},
 {cod:"NUT-05",especialidad:"Nutrición deportiva y del rendimiento",descripcion:"Acompaña al deportista y a la persona activa: periodiza la alimentación por fase de temporada y ajusta el rendimiento.",origen:"establecida",naturaleza:"rendimiento",
  empleo:3,empleo_txt:"SER UNO Nutrición «Nutricionista deportivo» (Lima); UPN/Laureate nutricionista para deportistas; aviso de campo con «consultoría nutricional y ISAK 1» S/ 2 400 [E-7][E-B6][E-11]; clubes y federaciones sin aviso.",negocio:4,negocio_txt:"Consultorios y centros fitness: Siéntete Fit enseña «cómo funciona la atención y gestión de un consultorio nutricional privado» [E-6].",
  funciones_n:7,funciones:"Valoración de la condición · requerimientos por fase · periodización · suplementación · hidratación · composición corporal · educación del equipo",proceso:"Valorar la condición → planificar la periodización → acompañar",evidencia:"Plan de periodización nutricional y registro de control de temporada",
  d_vol:3,d_amp:3,d_esc:2,d_rem:2,d_for:1,t_cre:4,t_nor:1,t_inv:4,t_dem:3,t_tec:4,i_cri:2,i_alc:3,sos:2,
  fd:"Jooble «deportiva» 736 (06-2026) → 1 013 (09-2026, cota); consultoras, universidades y gimnasios; remuneración dispersa S/ 1 320–2 400 en campo, jefaturas S/ 5 000–6 000 [E-11][E-B6][E-2]. Colegiatura no siempre exigida [E-11].",
  ft:"4 026 gimnasios, >2 M usuarios, penetración 6 %; Smart Fit 91 → 100 locales, utilidad +28 % en 2025; equipamiento +10 %/año [P-L12][P-S]. Ley 28036 sin mención al nutricionista; ISAK sin reconocimiento normativo (nivel 2) [N-5]. Wearables y apps maduras [P].",
  fi:"2 M usuarios de gimnasio; criticidad media. El segmento masivo (macros, planes genéricos) es sustituible por apps; la élite deportiva no [P].",refs:"E-2, E-6, E-7, E-11, E-B6; P-L12, P-S; N-5; O-tabla",procedencia:juicio},
 {cod:"NUT-06",especialidad:"Evaluación nutricional avanzada y composición corporal",descripcion:"Mide e interpreta la composición corporal con protocolos e instrumentos, y devuelve un informe a quien deriva.",origen:"emergente",naturaleza:"evaluación",
  empleo:2,empleo_txt:"Un solo aviso con «ISAK 1» como requisito (Panadería Central, administradora-nutricionista, S/ 2 400): tarea dentro de otro puesto [E-11]; la búsqueda devolvió solo oferta formativa (IIN/LAAM) [E-B9].",negocio:3,negocio_txt:"Servicio complementario en consulta privada y gimnasios [E-11].",
  funciones_n:5,funciones:"Protocolo ISAK · bioimpedancia y DEXA · calibración · interpretación e informe · seguimiento",proceso:"Recibir derivación → medir con protocolo → interpretar e informar",evidencia:"Informe de composición corporal con interpretación",
  d_vol:1,d_amp:2,d_esc:2,d_rem:2,d_for:1,t_cre:2,t_nor:1,t_inv:2,t_dem:3,t_tec:4,i_cri:3,i_alc:3,sos:1,
  fd:"Sin puestos propios; S/ 2 400 como tarea añadida [E-11].",ft:"Obesidad 15+ de 17,8 a 24,6 %; sarcopenia en población que envejece [P-S]. La medición se automatiza rápido (bioimpedancia, escaneo 3D, apps) [P].",
  fi:"Transversal; baja sostenibilidad como especialidad autónoma: sobrevive integrada a clínica, geriatría y deporte [P].",refs:"E-11, E-B9; P-S; O-tabla",procedencia:juicio},
 {cod:"NUT-07",especialidad:"Desarrollo y reformulación de productos alimentarios",descripcion:"Reformula el perfil nutricional de la cartera de la industria y sustenta su rotulado y registro sanitario.",origen:"emergente",naturaleza:"producto",
  empleo:3,empleo_txt:"Puesto compartido: Wasi Mikuna admite en la misma plaza «Nutrición, Bromatología y Nutrición, Ingeniería en Industrias Alimentarias, Ingeniería Alimentaria o Agroindustrial» [E-10]; Nestlé y Alicorp sin aviso específico [E-B10]; «Nutricionista Comercial» NC Company [E-B7].",negocio:3,negocio_txt:"Consultoría de rotulado y desarrollo para pymes de alimentos [E].",
  funciones_n:6,funciones:"Análisis de cartera · reformulación · validación sensorial · rotulado y octógonos · registro sanitario · vigilancia de la competencia",proceso:"Recibir la cartera → reformular → validar → registrar",evidencia:"Ficha técnica del producto reformulado y expediente de validación",
  d_vol:2,d_amp:3,d_esc:2,d_rem:2,d_for:1,t_cre:3,t_nor:3,t_inv:3,t_dem:3,t_tec:3,i_cri:3,i_alc:4,sos:4,
  fd:"Sin conteo; industria, comerciales de suplementos; 1 año de experiencia en I+D o control de calidad, colegiatura no mencionada [E-B10].",
  ft:"Snacks saludables USD 557 M (2025) → 989 M (2035, CAGR 5,9 %); reformulación por octógonos redujo azúcar −36,7 % y sodio −14 % en fase 1, con retroceso parcial desde 2021 [P-L6][P-L5]. Ley 30021 fase 2 vigente; NTP 209.038 «recomendable» sin firma reservada (nivel 2) [N-4][N-6].",
  fi:"Población consumidora total; reformulación «táctica» que evade octógonos sin mejorar salud [P-L5]. Validación sensorial y regulatoria no se automatizan [P].",refs:"E-10, E-B7, E-B10; P-L5, P-L6; N-4, N-6; O-tabla",procedencia:juicio},
 {cod:"NUT-08",especialidad:"Nutrición en obesidad y cirugía bariátrica",descripcion:"Atiende a la persona con obesidad y al paciente pre y posbariátrico: manejo de peso, deficiencias y conducta alimentaria.",origen:"emergente",naturaleza:"atención individual",
  empleo:3,empleo_txt:"Clínicas de salud y estéticas: «título en Nutrición, colegiatura y habilitación vigentes, mínimo 1 año en consulta nutricional» [E-B8]; Adelgazar y Punto Zen busca nutricionista [E-B13].",negocio:4,negocio_txt:"Centros de control de peso con 13 años de trayectoria; telenutrición [E-B13][P-S].",
  funciones_n:6,funciones:"Valoración · plan de manejo de peso · preparación prebariátrica · seguimiento posquirúrgico · deficiencias de micronutrientes · conducta alimentaria",proceso:"Valorar → planificar → intervenir → seguir",evidencia:"Plan de manejo nutricional con seguimiento documentado",
  d_vol:3,d_amp:3,d_esc:2,d_rem:2,d_for:3,t_cre:3,t_nor:2,t_inv:3,t_dem:4,t_tec:3,i_cri:3,i_alc:4,sos:3,
  fd:"Centros privados y clínicas estéticas; sin cifra de remuneración [E-B8][E-B13].",
  ft:"Obesidad 15+ 24,6 % (2020); comorbilidad 41,8 % (2025); ~8 M adultos con obesidad; sin datos de cirugía bariátrica en Perú (vacío); telenutrición validada en Lima [P-S][P-L1].",
  fi:"Alta comorbilidad; la consulta básica es sustituible por apps, el manejo clínico-quirúrgico no [P].",refs:"E-B8, E-B13; P-L1, P-S; O-tabla",procedencia:juicio},
 {cod:"NUT-09",especialidad:"Nutrición ocupacional y salud en minería",descripcion:"Atiende la alimentación y el estado nutricional del trabajador en campamentos y programas de salud ocupacional.",origen:"emergente",naturaleza:"atención individual",
  empleo:4,empleo_txt:"NATCLAR (salud ocupacional) «Nutricionista Unidad Minera La Oroya», habilitación indispensable [E-12]; Centro de Investigación de la Salud y el Trabajo (Surco) aviso a S/ 8 000 [E-6].",negocio:3,negocio_txt:"Consultoría en salud ocupacional para contratistas mineros [E-12].",
  funciones_n:6,funciones:"Valoración del trabajador · plan alimentario de campamento · vigilancia de riesgo cardiometabólico · educación · articulación con salud ocupacional · indicadores",proceso:"Valorar al trabajador → planificar → intervenir → vigilar",evidencia:"Programa nutricional ocupacional con indicadores de salud del trabajador",
  d_vol:2,d_amp:2,d_esc:3,d_rem:4,d_for:3,t_cre:3,t_nor:2,t_inv:3,t_dem:2,t_tec:2,i_cri:3,i_alc:3,sos:4,
  fd:"Pocos avisos pero con remuneración muy sobre el promedio (S/ 8 000) y habilitación exigida [E-6][E-12]. Especialidad descubierta en el barrido.",
  ft:"10+ proyectos mineros en 2026; contratistas de salud ocupacional y concesionarias en expansión [P-S][E-B5]. Sin norma específica.",
  fi:"Salud de trabajadores en régimen de campamento; criticidad alta por riesgo cardiometabólico [P].",refs:"E-6, E-12, E-B5; P-S",procedencia:juicio},
 {cod:"NUT-10",especialidad:"Nutrición en programas sociales del Estado",descripcion:"Gestiona el componente alimentario y nutricional de programas del MIDIS y gobiernos locales por unidad territorial.",origen:"establecida",naturaleza:"salud poblacional",
  empleo:4,empleo_txt:"CAS 094 «Especialista Alimentario» Áncash S/ 3 200 por unidad territorial [E-10]; PAE en Puno, Huánuco, Cajamarca, Arequipa; Cuna Más Lima e Ica [E-1].",negocio:1,negocio_txt:"Dependiente del Estado.",
  funciones_n:6,funciones:"Fichas técnicas · supervisión de proveedores · vigilancia sanitaria · capacitación · monitoreo · reporte",proceso:"Planificar la atención → supervisar → vigilar → reportar",evidencia:"Informe de supervisión de la unidad territorial con indicadores",
  d_vol:3,d_amp:2,d_esc:2,d_rem:2,d_for:3,t_cre:1,t_nor:3,t_inv:4,t_dem:3,t_tec:3,i_cri:4,i_alc:4,sos:4,
  fd:"Wasi Mikuna: de 1 convocatoria (06-2025) a 0 vigentes (09-2026); admite carreras afines [E-10][E-4]. Misma naturaleza que comunitaria: candidata a integración.",
  ft:"PAE 2026 S/ 2 636,6 M, 4,2 M escolares, 67 000 II. EE.; dos programas disueltos en 18 meses (Qali Warma, Wasi Mikuna) [P-L4][N-10]; fichas técnicas obligatorias vía Perú Compras [P-L4].",
  fi:"4,2 M escolares; fallas = intoxicaciones masivas (2024). Supervisión in situ no se automatiza [P].",refs:"E-1, E-4, E-10; P-L4; N-10; O-tabla",procedencia:juicio},
 {cod:"NUT-11",especialidad:"Consultoría privada y nutrición online",descripcion:"Atiende por consulta particular presencial o virtual y coaching remoto.",origen:"establecida",naturaleza:"consultoría",
  empleo:2,empleo_txt:"Start-ups de coaching: «colaboración a tiempo parcial con horarios flexibles y contrato freelance»; Nutrizales «asesoría nutricional a clientes en diferentes distritos» S/ 1 320 [E-B14][E-6].",negocio:4,negocio_txt:"Consultorio propio; La República señala la consulta particular presencial o virtual como sector de mayor demanda [E-2].",
  funciones_n:4,funciones:"Consulta · plan · seguimiento remoto · marca profesional",proceso:"Recibir al cliente → evaluar → pautar → seguir",evidencia:"Plan nutricional individual con seguimiento",
  d_vol:3,d_amp:3,d_esc:1,d_rem:1,d_for:1,t_cre:3,t_nor:1,t_inv:2,t_dem:3,t_tec:4,i_cri:2,i_alc:3,sos:1,
  fd:"Jooble «online» 913 (01-2026); remoto desde S/ 1 800; freelance sin colegiatura [E-B14].",ft:"Telenutrición evaluada en Lima; apps con IA que producen planes «en minutos» [P-S]. La más expuesta a la IA [P].",
  fi:"Criticidad baja-media; riesgo de intrusismo. Es un modo de ejercicio de otras especialidades más que un campo propio [P].",refs:"E-2, E-6, E-B14; P-S",procedencia:juicio},
 {cod:"NUT-12",especialidad:"Nutrición renal y diálisis",descripcion:"Atiende al paciente con enfermedad renal crónica en prevención, diálisis y trasplante.",origen:"emergente",naturaleza:"atención individual",
  empleo:2,empleo_txt:"Ningún aviso de centro de diálisis en el barrido [E-B13]; tarea dentro del puesto clínico.",negocio:2,negocio_txt:"Complemento en consulta clínica; Wiener ofrece segunda especialidad en Nutrición Renal [N-7].",
  funciones_n:5,funciones:"Valoración renal · prescripción de proteínas y electrolitos · manejo en diálisis · desnutrición urémica · trasplante",proceso:"Valorar → prescribir → seguir en diálisis",evidencia:"Plan nutricional renal con control de laboratorio",
  d_vol:1,d_amp:2,d_esc:3,d_rem:3,d_for:4,t_cre:3,t_nor:2,t_inv:3,t_dem:4,t_tec:3,i_cri:4,i_alc:3,sos:4,
  fd:"Sin puesto diferenciado en portales [E-B13].",ft:">3 M con ERC, 23 000 que deberían dializarse, ingreso a diálisis +8 %/año en EsSalud, GPC ERC de diciembre de 2025 [P-L9][P-S].",
  fi:"Mortalidad directa por mala nutrición en diálisis; muy alta sostenibilidad [P].",refs:"E-B13; P-L9, P-S; N-7",procedencia:juicio},
 {cod:"NUT-13",especialidad:"Nutrición oncológica",descripcion:"Atiende al paciente en tratamiento oncológico: manejo de síntomas, soporte y seguimiento post-tratamiento.",origen:"establecida",naturaleza:"atención individual",
  empleo:2,empleo_txt:"Un aviso (Mundo Sin Cáncer, Lima) [E-B13]; INEN sin aviso; en la práctica es tarea dentro del puesto clínico.",negocio:2,negocio_txt:"Complemento en consulta; Wiener ofrece segunda especialidad con mención oncológica (posgrado) [O-tabla].",
  funciones_n:5,funciones:"Tamizaje · valoración en tratamiento · manejo de síntomas · cuidados paliativos · seguimiento",proceso:"Valorar → diagnosticar → tratar → seguir (paciente oncológico)",evidencia:"Plan de atención nutricional individualizado",
  d_vol:2,d_amp:2,d_esc:3,d_rem:3,d_for:3,t_cre:3,t_nor:2,t_inv:2,t_dem:4,t_tec:2,i_cri:4,i_alc:3,sos:4,
  fd:"Acotada a institutos y unidades especializadas [E-B13].",ft:">80 000 casos nuevos/año, mortalidad +26 % en 5 años, 56–70 % diagnosticados en estadios III-IV [P-L10]; sin línea presupuestal de nutrición [P].",
  fi:"Toxicidad y abandono de tratamiento sin soporte; sin dato peruano de desnutrición oncológica (vacío) [P].",refs:"E-B13; P-L10; O-tabla",procedencia:juicio},
 {cod:"NUT-14",especialidad:"Nutrición geriátrica y del envejecimiento",descripcion:"Atiende al adulto mayor: desnutrición, sarcopenia, disfagia y adaptación de texturas en residencias y consulta.",origen:"emergente",naturaleza:"atención individual",
  empleo:2,empleo_txt:"Ningún aviso menciona geriatría o residencias [E]; tarea dentro del puesto clínico.",negocio:3,negocio_txt:"Consulta y residencias privadas; sin cifra.",
  funciones_n:4,funciones:"Tamizaje del adulto mayor · sarcopenia · texturas y disfagia · seguimiento en residencias",proceso:"Valorar → diagnosticar → tratar → seguir (adulto mayor)",evidencia:"Plan de atención nutricional individualizado",
  d_vol:1,d_amp:2,d_esc:2,d_rem:2,d_for:2,t_cre:2,t_nor:2,t_inv:2,t_dem:4,t_tec:2,i_cri:3,i_alc:4,sos:4,
  fd:"Sin plaza con ese nombre [E].",ft:"60+ = 14,3 % de la población en 2025 (~4,9 M) y superarán a los <15 en 2050; dependencia de vejez 23 → 41,5 %: el driver demográfico más sólido del campo [P-S]. Casi ausente en la oferta académica (nivel 4) [O-tabla].",
  fi:"Hospitalización evitable por sarcopenia, disfagia y polifarmacia; muy alta sostenibilidad [P].",refs:"P-S; O-tabla",procedencia:juicio},
 {cod:"NUT-15",especialidad:"Soporte nutricional parenteral y enteral",descripcion:"Formula y monitorea la mezcla parenteral y el soporte enteral cuando el equipo clínico lo interconsulta.",origen:"establecida",naturaleza:"atención individual",
  empleo:2,empleo_txt:"Sin puesto separado; Tarapoto admite «soporte crítico (mínimo 90 h)» como especialización dentro de la plaza [E-9].",negocio:1,negocio_txt:"No sostiene negocio propio.",
  funciones_n:2,funciones:"Cálculo y formulación · monitoreo metabólico",proceso:"Recibir interconsulta → formular → monitorear",evidencia:"Prescripción de fórmula parenteral",
  d_vol:2,d_amp:2,d_esc:3,d_rem:3,d_for:4,t_cre:2,t_nor:3,t_inv:3,t_dem:3,t_tec:3,i_cri:4,i_alc:2,sos:4,
  fd:"Se contrata dentro del equipo de soporte del hospital [E-9].",ft:"NTS 212 (RM 203-2024): la preparación de mezclas es competencia de farmacia (nivel 1 para esa tarea); el nutricionista integra el equipo (nivel 3) [N-7]. Prematuridad 22,1 % y cáncer como demanda derivada [P].",
  fi:"Pacientes críticos; nicho estable [P].",refs:"E-9; N-7; P",procedencia:juicio},
 {cod:"NUT-16",especialidad:"Educación alimentaria escolar",descripcion:"Dicta sesiones educativas en la escuela y articula con el quiosco escolar y las familias.",origen:"establecida",naturaleza:"salud poblacional",
  empleo:2,empleo_txt:"Docencia por horas (categoría «docente nutricionista» en Jooble); sin puesto en colegios [E-B15].",negocio:2,negocio_txt:"Complemento de ingresos; talleres.",
  funciones_n:3,funciones:"Sesiones educativas · material didáctico · quiosco escolar",proceso:"Diagnosticar → educar → evaluar (escolares)",evidencia:"Plan de sesión educativa",
  d_vol:2,d_amp:2,d_esc:1,d_rem:1,d_for:1,t_cre:1,t_nor:3,t_inv:2,t_dem:3,t_tec:3,i_cri:2,i_alc:3,sos:3,
  fd:"No existe el puesto: la ejercen el docente y el programa [E].",ft:"Ley 30021 / DS 017-2017-SA: quioscos y comedores escolares solo con alimentos saludables (nivel 3) [N-4]; PAE con 4,2 M escolares, componente educativo no desagregado [P-L4].",
  fi:"Riesgo de absorción por docentes; efecto de octógonos anulado sin educación [P-L5].",refs:"E-B15; P-L4, P-L5; N-4",procedencia:juicio},
 {cod:"NUT-17",especialidad:"Nutrición personalizada y nutrigenómica",descripcion:"Interpreta perfiles genéticos y los traduce a pautas dietéticas individuales.",origen:"emergente",naturaleza:"evaluación",
  empleo:1,empleo_txt:"Ningún aviso en el barrido [E].",negocio:3,negocio_txt:"Consulta privada de alto ingreso con laboratorio asociado.",
  funciones_n:2,funciones:"Interpretación del perfil · traducción a pauta",proceso:"Recibir perfil → interpretar → pautar",evidencia:"Informe de interpretación nutrigenómica",
  d_vol:1,d_amp:1,d_esc:2,d_rem:3,d_for:1,t_cre:2,t_nor:1,t_inv:2,t_dem:2,t_tec:2,i_cri:2,i_alc:1,sos:2,
  fd:"Sin puestos en el país [E].",ft:"Sin cifras peruanas; el CNP la lleva a su congreso; evidencia clínica limitada [P-S].",
  fi:"Bajo alcance; emergente-especulativa, recomendable como electivo [P].",refs:"P-S; O-tabla",procedencia:juicio},
 {cod:"NUT-18",especialidad:"Informática nutricional e IA aplicada",descripcion:"Automatiza tamizaje, cálculo y registro dentro del trabajo de las demás especialidades.",origen:"emergente",naturaleza:"transversal",
  empleo:1,empleo_txt:"No aparece en ninguna búsqueda ni aviso [E].",negocio:2,negocio_txt:"Complemento; no campo de ejercicio.",
  funciones_n:0,funciones:"Atraviesa las funciones de todas las especialidades",proceso:"Atraviesa varios procesos profesionales",evidencia:"No entrega evidencia profesional propia",
  d_vol:1,d_amp:2,d_esc:3,d_rem:3,d_for:1,t_cre:4,t_nor:2,t_inv:3,t_dem:3,t_tec:2,i_cri:3,i_alc:4,sos:4,
  fd:"Sin puestos con ese nombre [E].",ft:"Revisión peruana (Rebagliati, 12-2025) identifica cuatro usos hospitalarios de la IA; telenutrición; apps [P-L11]. Emergente fuerte, perfil híbrido.",
  fi:"Tecnología habilitante: recurso de productividad del paso 2.2, no especialidad [método].",refs:"P-L11",procedencia:juicio},
 {cod:"NUT-19",especialidad:"Dietética hospitalaria operativa",descripcion:"Programa y despacha las raciones según el ciclo de menús que define el servicio.",origen:"en extinción",naturaleza:"gestión de servicios",
  empleo:3,empleo_txt:"«Auxiliar de Nutrición… Jornada: Interdiario» en Maison de Santé, Javier Prado y Sodexo; secundaria o técnico, 6 meses de experiencia, S/ 1 200 + movilidad [E-7][E-13].",negocio:1,negocio_txt:"No sostiene negocio propio.",
  funciones_n:3,funciones:"Programación de raciones · despacho · control diario",proceso:"Recibir ciclo de menús → producir → despachar",evidencia:"Parte de producción diaria",
  d_vol:3,d_amp:2,d_esc:1,d_rem:1,d_for:1,t_cre:1,t_nor:1,t_inv:2,t_dem:1,t_tec:4,i_cri:2,i_alc:2,sos:1,
  fd:"Puesto de auxiliar sin colegiatura, que compite con el titulado hacia abajo [E-7].",ft:"Planificación, cálculo y asignación de dietas automatizables; converge con servicios de alimentación [P].",
  fi:"Contracción como puesto de cálculo [P].",refs:"E-7, E-13; P",procedencia:juicio}
];

/* Regla del puesto: con empleo ≤ 2 y negocio ≤ 2 la candidata no se valora (sin potencial) y va a la Fase 2 como función;
   una tecnología transversal es recurso del paso 2.2; el origen «en extinción» sale del alcance. Destinos provisionales hasta M5. */
function depurar(f){ f.forEach(x=>{
  if(x.naturaleza==="transversal"){ x.destino="Recurso del 2.2 (provisional)"; x.motivo="Atraviesa todas las especialidades: tecnología habilitante, no campo de ejercicio"; }
  else if(x.empleo<=2&&x.negocio<=2){ x.destino=(x.t_dem>=4)?"Esperar y revisar (provisional)":"Va a la Fase 2 (provisional)"; x.motivo="Regla del puesto: no se contrata como puesto propio ni sostiene negocio propio; sus tareas se recogen como función"; ["d_vol","d_amp","d_esc","d_rem","d_for","t_cre","t_nor","t_inv","t_dem","t_tec","i_cri","i_alc","sos"].forEach(k=>{ x["j_"+k]=x[k]; }); x.procedencia+=" Devuelta por la regla del puesto: no se valora; las puntuaciones se conservan solo como registro del barrido."; }
  else if(x.origen==="en extinción"){ x.destino="No entra (provisional)"; x.motivo="Origen en extinción: sale del alcance con motivo declarado"; }
 }); return f }
module.exports={SIS,NUT,depurar};
if(require.main!==module) return;
const fSIS=escribir(R("cartera-SIS.csv"),depurar(SIS)), fNUT=escribir(R("cartera-NUT.csv"),depurar(NUT));
const resumen=(n,f)=>{ const val=f.filter(x=>!(x.empleo<=2&&x.negocio<=2)&&x.naturaleza!=="transversal");
 console.log("== "+n+": "+f.length+" candidatas · "+val.length+" valoradas · "+(f.length-val.length)+" devueltas (regla del puesto o transversal)");
 [...f].sort((a,b)=>(b.POT||0)-(a.POT||0)).forEach(x=>console.log(String(x.POT??"—").padStart(3),x.empleo+"/"+x.negocio,x.cod,x.especialidad)) };
resumen("SIS",fSIS); resumen("NUT",fNUT);
