/* Línea base literal del plan vigente de Nutrición Humana (entregada por la Escuela el 24-09-2026), clasificada según el método:
   A = de especialidad (entra al contraste) · C = dominio disciplinar (se declara, no se rediseña aquí). */
const fs=require("fs"),path=require("path");
const C=(n,np,d,caps,cd,tipo,nota)=>({n,np,d,caps,cd,tipo,nota});
const plan={cod:"NUT",fuente:"Formulación literal entregada por la Escuela el 24-09-2026 (competencias del plan vigente, tal como están escritas)",
 competencias:[
  C("Nutrición y salud","Competencia 1 · plan vigente","Propone planes de intervención basados en el proceso de atención nutricional de acuerdo a la situación fisiopatológica, sociocultural, económica y sanitaria de la persona para fomentar cambios en el estilo de vida, promover salud y prevenir la enfermedad.",
   ["Evaluación nutricional","Diagnóstico nutricional","Intervención nutricional","Monitoreo nutricional"],
   ["Argumenta el proceso de evaluación nutricional en función a los métodos y herramientas seleccionados para la recolección de datos requeridos considerando la situación fisiopatológica.","Argumenta el diagnóstico nutricional considerando la definición del problema, su etiología, los signos y síntomas para proponer estrategias de intervención nutricional.","Elabora un plan de intervención nutricional oportuno acorde a la situación fisiopatológica, sociocultural, económica y sanitaria de la persona para modificar positivamente conductas relacionadas a la salud y nutrición.","Valora los resultados de la intervención nutricional durante el proceso de seguimiento a la persona, identificando de forma oportuna los cambios positivos o negativos para hacer los ajustes necesarios, alcanzar los objetivos y mejorar el estado de salud y nutrición."],"A",""),
  C("Ciencia de los alimentos","Competencia 2 · plan vigente","Desarrolla productos alimentarios y/o fórmulas nutricionales de acuerdo a la normativa nacional e internacional vigentes para satisfacer las necesidades nutricionales en las diferentes etapas de vida del consumidor y contribuir con la salud y seguridad alimentaria.",
   ["Formulación de producto","Desarrollo del producto","Promoción y comunicación"],
   ["Formula las características del producto que se introducirá al mercado, considerando los requerimientos nutricionales y el perfil del consumidor para fomentar su posicionamiento y contribuir con la salud.","Diseña productos alimenticios innovadores considerando los aspectos socioculturales, gastronómicos, nutritivos y legales para contribuir con la seguridad alimentaria y el bienestar del consumidor.","Establece estrategias técnicas y prácticas que agregan valor al producto/servicio y promocionen la adopción de actitudes y comportamientos saludables conscientes en el consumidor."],"A",""),
  C("Gestión en nutrición y alimentos","Competencia 3 · plan vigente","Gestiona servicios de nutrición y alimentos, asegurando procesos de calidad y la incorporación de tecnologías emergentes y prácticas innovadoras que contribuyan a la seguridad alimentaria, aplicadas de forma ética y sostenible, y alineadas con los estándares de seguridad alimentaria y las necesidades nutricionales de la población.",
   ["Gestión de servicios de nutrición y alimentación","Incorporación de tecnologías emergentes","Seguridad alimentaria y sostenibilidad"],
   ["Gestiona eficientemente servicios de nutrición y alimentación, enfocándose en la calidad y la innovación adaptados a las nuevas tendencias del mercado y necesidades de la población.","Implementa y adapta tecnologías emergentes y prácticas innovadoras en la gestión de la nutrición y los alimentos.","Asegura que los servicios y productos cumplan con los estándares de seguridad alimentaria y sostenibilidad, respetando el medio ambiente y las necesidades nutricionales."],"A",""),
  C("Gestión del proceso de atención nutricional","Competencia 4 · plan vigente","Evalúa, diagnostica, interviene y monitorea la situación nutricional y metabólica de las personas con patologías específicas, aplicando eficazmente la evidencia científica y protocolos vigentes, considerando el estado clínico, factores fisiológicos, fisiopatológicos y probable interacción fármaco-nutriente, con enfoque holístico centrado en el paciente y en colaboración con el equipo interdisciplinario, contribuyendo así a la mejora de la salud y bienestar.",
   ["Evaluación y diagnóstico avanzado","Intervención nutricional personalizada","Monitoreo y ajuste continuo"],
   ["Realiza evaluaciones nutricionales y metabólicas profundas, utilizando tecnologías emergentes y métodos de diagnóstico innovadores.","Diseña e implementa intervenciones nutricionales basadas en la genómica y la nutrigenómica, adaptadas a las necesidades individuales.","Monitorear y ajustar los planes de nutrición en tiempo real, utilizando tecnologías de seguimiento y análisis de datos avanzados."],"A",""),
  C("Gestión de la atención nutricional integral de la comunidad","Competencia 5 · plan vigente","Diseña, implementa y evalúa programas y políticas de salud pública en nutrición, integrando equipos interdisciplinarios, con el propósito de prevenir o controlar eficazmente y con evidencia científica la problemática alimentario nutricional que afecta la salud de diversas poblaciones, actuando de manera ética, inclusiva, respetando la diversidad cultural y las necesidades específicas de las comunidades.",
   ["Diseño y evaluación de programas de salud pública","Gestión de problemas alimentario-nutricionales"],
   ["Desarrolla y evalúa programas y políticas de nutrición para la salud pública, utilizando enfoques basados en la evidencia y tecnologías de la información.","Identifica y aborda problemas alimentarios y nutricionales en diferentes poblaciones, con un enfoque en la prevención y el control."],"A",""),
  C("Gestión de proyectos en nutrición y alimentos","Competencia 6 · plan vigente","Gestiona servicios de nutrición y alimentos, asegurando procesos de calidad y la incorporación de tecnologías emergentes y prácticas innovadoras que contribuyan a la seguridad alimentaria, aplicadas de forma ética y sostenible, y alineadas con los estándares de seguridad alimentaria y las necesidades nutricionales de la población.",
   ["Gestión de servicios de nutrición y alimentación","Incorporación de tecnologías emergentes","Seguridad alimentaria y sostenibilidad"],
   ["Gestiona eficientemente servicios de nutrición y alimentación, enfocándose en la calidad y la innovación adaptados a las nuevas tendencias del mercado y necesidades de la población.","Implementa y adapta tecnologías emergentes y prácticas innovadoras en la gestión de la nutrición y los alimentos.","Asegura que los servicios y productos cumplan con los estándares de seguridad alimentaria y sostenibilidad, respetando el medio ambiente y las necesidades nutricionales."],"A","Definición y capacidades idénticas, palabra por palabra, a «Gestión en nutrición y alimentos»: solo cambia el título."),
  C("Promoción de nutrición, alimentación y estilo de vida saludable","Competencia 7 · plan vigente","Educa y promueve la práctica de estilos de vida saludables, integrando el equilibrio nutricional y actividad física, para mejorar el bienestar general de individuos y comunidades, alineadas con principios de salud integral y métodos educativos basados en la evidencia y prácticas innovadoras.",
   ["Educación y promoción de estilos de vida saludables / gastronomía y aplicación práctica en nutrición","Desarrollo de programas integrales de bienestar","Innovación y adaptación de métodos educativos"],
   ["Educa y promueve estilos de vida que integren un equilibrio nutricional y actividad física, utilizando métodos educativos basados en la evidencia.","Diseña programas integrales que mejoren el bienestar general, considerando aspectos nutricionales, físicos y psicológicos.","Implementa, integra y adapta los principios de salud adventistas en la práctica nutricional, empleando métodos educativos y tecnologías innovadoras para promover la salud nutricional y estilos de vida saludables."],"A",""),
  C("Fundamentos básicos de la nutrición","Competencia 8 · plan vigente","Aplica conocimientos especializados en bioquímica, morfofisiología, microbiología y bromatología para evaluar y manejar la nutrición y la salud en contextos clínicos y comunitarios.",
   ["Biológicos y fisiológicos","Salud y enfermedad","Seguridad y composición de los alimentos"],
   ["Estudiar y comprender los procesos biológicos y fisiológicos humanos en relación con la nutrición: absorción, metabolismo y utilización de los nutrientes, metabolismo energético, macro y micronutrientes, regulación hormonal del apetito y relación entre nutrición y fisiología de órganos y sistemas.","Relacionar la nutrición con la promoción y prevención de la salud y el manejo de enfermedades: prevención de enfermedades crónicas, nutrición en las etapas de la vida y en la gestión de condiciones de salud; deficiencias y excesos de nutrientes.","Calidad, seguridad y composición nutricional de los alimentos: componentes, higiene, prevención de la contaminación y de las enfermedades transmitidas por alimentos, técnicas de procesamiento, conservación y preparación y su impacto en la nutrición y la salud."],"C","Dominio disciplinar (bioquímica, morfofisiología, microbiología, bromatología): no se rediseña en este paso; se deriva en el paso 3.4. Se declara y queda fuera del contraste.")],
 notas:["Siete unidades son de especialidad (tipo A) y entran al contraste; «Fundamentos básicos de la nutrición» es de dominio disciplinar (tipo C) y se declara fuera.","«Gestión de proyectos en nutrición y alimentos» repite literalmente a «Gestión en nutrición y alimentos»: se conserva en la línea base como está y el contraste lo registra como gatillo de fusión.","Las definiciones de «Fundamentos básicos» se resumieron para la ficha; el texto completo entregado queda como referencia en la conversación de la Escuela."]};
fs.writeFileSync(path.join(__dirname,"..","datos","plan-vigente","NUT-plan.json"),JSON.stringify(plan,null,1));
console.log("NUT plan:",plan.competencias.length,"unidades ·",plan.competencias.filter(c=>c.tipo==="A").length,"de especialidad ·",plan.competencias.reduce((s,c)=>s+c.caps.length,0),"capacidades");
